# Lab Week 14 Part 2: LU Decomposition

**You will only turn in your HANDWRITTEN answers for this notebook.**

**I have provided code in this notebook that will help you check your answers in Python if you wish to do so.**

You are encouraged to use:
* [Python for Linear Algebra Reference Sheet](https://humboldt.cloudbank.2i2c.cloud/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fbludka%2Fengr225-materials-fa2024&branch=main&urlpath=lab%2Ftree%2Fengr225-materials-fa2024%2F00_resources%2FPython_Toolbox_for_Linear_Algebra.ipynb)
* [Methods to Solve Systems of Equations Review](https://humboldt.cloudbank.2i2c.cloud/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fbludka%2Fengr225-materials-fa2024&branch=main&urlpath=lab%2Ftree%2Fengr225-materials-fa2024%2F00_resources%2FSolving_Systems_of_Eqns_Review.ipynb)


Run the following code to import numpy and chose a more convenient output format

In [2]:
import numpy as np
np.set_printoptions(precision=4,suppress=True)

## 1. Elementary Matrices

An **elementary matrix**, $E$, is a matrix that **represents an elementary row operation**.

An elementary matrix is obtained by performing a row operation on the identity matrix.

Multiplying $E$ on the LEFT of another matrix (let's call it $A$) is equivalent to performing a row operation on $A$.


### 1.1 Switching Rows

Let's look at an example of an elementary matrix that represents a row switch.

Start with the identity matrix

$ I = \begin{bmatrix}
1 & 0 & 0\\
0 & 1 & 0 \\
0 & 0 & 1
\end{bmatrix} $


Apply a row switch operation
$ {R}_0 \leftrightarrow \text{R}_1 $

The matrix becomes:

$E_{switchR0R1} = \begin{bmatrix}
0 & 1 & 0\\
1 & 0 & 0 \\
0 & 0 & 1
\end{bmatrix}$

In [ ]:
#Using Python:
I = np.identity(3)
R0 = np.copy(I[0,:])
R1 = np.copy(I[1,:])
E = np.copy(I)
E[1,:] = R0
E[0,:] = R1
print(E)

[[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]


Test your elementry matrix by multiplying it on the LEFT side of another matrix of the same size.

$EA=?$

Did it switch the rows of $A$?

$ {R}_0 \leftrightarrow \text{R}_1 $?

In [ ]:
A = np.array([[1., 1., 5.],  #R0
              [0., 2., 2.],  #R1
              [1., 0., 0.]]) #R2

print(E@A)

[[0. 2. 2.]
 [1. 1. 5.]
 [1. 0. 0.]]


#### Question 1.1.1 - [2pts]

Following the example above...

a.) What is the 3x3 Elementary Matrix that represents the following row switch?:

$$ {R}_0 \leftrightarrow \text{R}_2 $$

Then, show how to derive this Elementary Matrix, starting from the 3x3 Idenity matrix.

In [4]:
#You can check your answer here
I = np.identity(3)
R0 = np.copy(I[0,:])
R2 = np.copy(I[2,:])
E = np.copy(I)
E[2,:] = R0
E[0,:] = R2
print(E)

[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]


b.) Multiply your elementary matrix by another 3x3 matrix (you can make it up) to test if your elementry matrix works the way you think it should work. Do this by hand (showing all steps). 

If you would like to check your work using Python, use the @ operator for matrix multiplication.

Note: Make sure your work is useful for our task. (Please don't just multiply by a zero matrix. You won't receive points for something like that.)

In [5]:
#You can check your answer here
A = np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])
print(E@A)

[[7. 8. 9.]
 [4. 5. 6.]
 [1. 2. 3.]]


As a reminder,

Matrices can only be multiplied if their inner dimensions are equal. Multiplying $A$ with dimensions $m$ x $n$, by $B$ with dimensions $n$ x $p$, results in a matrix $AB$ of size $m$ x $p$.

<img src="https://lh3.googleusercontent.com/pw/ADCreHcSe-OO0Eh4TlZyt0RYkgpbCN79xoF0AUhV7yAJZWp1a-miuOhNnOR_M2zjdX14guNXEhFzT144A-bOzLDoSc_OLo_50S5DNwSIJot7mDI1xsvrDkrfjAXSuXsHIiFgzc0JxZ_6mGEEC2M6TR_w3jcv=w584-h371-s-no?authuser=0" width="350">

Matrix multiplication follows the row-column rule.

<img src="https://lh3.googleusercontent.com/pw/ADCreHdYJ6RYsDC9eDW-1SuX4Q1MdewyfC4pCMF9r3vOKesFMTrTkqF-JklZSAxXk0p0MVioYObI405XxPpVSVkQayTJsi_Js9-NSrLm932t1gsNvWU680Jrs_4D5n_iJo3HoEu-aZGT8G_8O2BsQy_gDUsk=w1400-h848-s-no?authuser=0" width="350">

***When I ask you to show all your matrix multiplication steps by hand, please do it like the example figure above.***

### 1.2 Multiply a row by a non-zero number

Let's look at an example of an elementary matrix that represents multiplying a row by a non-zero number.

Start with the identity matrix

$ I = \begin{bmatrix}
1 & 0 & 0\\
0 & 1 & 0 \\
0 & 0 & 1
\end{bmatrix} $


Apply the row operation
$$ 3\text{R}_1 \rightarrow \text{R}_1 $$

The matrix becomes:

$E_{3R1} = \begin{bmatrix}
1 & 0 & 0\\
0 & 3 & 0 \\
0 & 0 & 1
\end{bmatrix}$

In [ ]:
#Using Python
I = np.identity(3)
E = np.copy(I)
E[1,:] = 3*E[1,:]
print(E)

[[1. 0. 0.]
 [0. 3. 0.]
 [0. 0. 1.]]


Test your elementry matrix by multiplying it on the left side of another matrix of the same size.

$EA=?$

Did it multiply the middle row by 3?

$ 3\text{R}_1 \rightarrow \text{R}_1 $?

In [ ]:
A = np.array([[1., 1., 5.],  #R0
              [0., 2., 2.],  #R1
              [1., 0., 0.]]) #R2

print(E@A)

[[1. 1. 5.]
 [0. 6. 6.]
 [1. 0. 0.]]


#### Question 1.2.1 - [2pts]
a.) What is the 3x3 Elementary Matrix that represents multiplying the last row by 2?
$$ 2\text{R}_2 \rightarrow \text{R}_2 $$


Then, show how to derive this Elementary Matrix, starting from the 3x3 Idenity matrix.

In [7]:
#You can check your answer here
I = np.identity(3)
E = np.copy(I)
E[2,:] = 2*E[2,:]
print(E)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 2.]]


b.) Multiply your elementary matrix by another 3x3 matrix (you can make it up) to test if your elementry matrix works the way you think it should work. 

If you would like to check your work using Python, use the @ operator for matrix multiplication.

In [8]:
#You can check your answer here
A = np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])
print(E@A)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [14. 16. 18.]]


### 1.3 Replace a row by itself plus multiple of another row

Let's look at an example of an elementary matrix that represents replacing a row by itself plus a multiple of another row.

Start with the identity matrix

$ I = \begin{bmatrix}
1 & 0 & 0\\
0 & 1 & 0 \\
0 & 0 & 1
\end{bmatrix} $

Apply the row operation
$$ 2 \text{R}_0 + \text{R}_2 \rightarrow \text{R}_2 $$

The matrix becomes:

$E_{R2+2*R0} = \begin{bmatrix}
1 & 0 & 0\\
0 & 1 & 0 \\
2 & 0 & 1
\end{bmatrix}$

In [10]:
#Using Python
I = np.identity(3)
E = np.copy(I)
E[2,:] = 2*E[0,:] + E[2,:]
print(E)

[[1. 0. 0.]
 [0. 1. 0.]
 [2. 0. 1.]]


Test your elementry matrix by multiplying it on the left side of another matrix of the same size.

$EA=?$

Did it perform the expected row operation?

$ \text{R}_2 + 2 \text{R}_0 \rightarrow \text{R}_2 $?

In [ ]:
A = np.array([[1., 1., 5.],  #R0
              [0., 2., 2.],  #R1
              [1., 0., 0.]]) #R2

print(E@A)

[[ 1.  1.  5.]
 [ 0.  2.  2.]
 [ 3.  2. 10.]]


Here is a video about these types of Elementary Matrices in case you find it helpful:

https://www.youtube.com/watch?v=Nxs_OARoUgE&list=PLkZjai-2Jcxlg-Z1roB0pUwFU-P58tvOx&index=14



#### Question 1.3.1 - [2pts]

a.) What is the 3x3 Elementary Matrix that represents the following row operation?:
$$ - 4 \text{R}_1 + \text{R}_0  \rightarrow \text{R}_0 $$


Then, show how to derive this Elementary Matrix, starting from the 3x3 Idenity matrix.

In [13]:
#You can check your answer here
I = np.identity(3)
E = np.copy(I)
E[0,:] = -4*E[1,:] + E[0,:]
print(E)

[[ 1. -4.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


b.) Multiply your elementary matrix by another 3x3 matrix (you can make it up) to test if your elementry matrix works the way you think it should work. 

If you would like to check your work using Python, use the @ operator for matrix multiplication.

In [14]:
#You can check your answer here
A = np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])
print(E@A)

[[-15. -18. -21.]
 [  4.   5.   6.]
 [  7.   8.   9.]]


## 2. Inverse of an Elementary Matrix

### 2.1 Inverse of the Row Switch Elementary Matrix

Remember that the inverse of an elementary matrix has the property that $E^{-1}E = I$ and $EE^{-1}=I$

So if

$E_{switchR0R1} = \begin{bmatrix}
0 & 1 & 0\\
1 & 0 & 0 \\
0 & 0 & 1
\end{bmatrix}$

Then in order to recover the inverse matrix, we need to switch the top rows $ {R}_0 \leftrightarrow \text{R}_1 $

... which we can do by multiplying it by itself!

...which means it is its own inverse!

$E_{switchR0R1} = E_{switchR0R1}^{-1}$



In [ ]:
#Using Python

#original
I = np.identity(3)
R0 = np.copy(I[0,:])
R1 = np.copy(I[1,:])
E = np.copy(I)
E[1,:] = R0
E[0,:] = R1
print("E=")
print(E)

#inverse is itself!
#Einv = E

#check it
print("EE=")
print(E@E)

E=
[[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]
EE=
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### Question 2.1.1 - [2pts]

a.) What is the inverse of the elementary matrix from Question 1.1.1?

In [ ]:
#You can check your answer here

b.) Check to make sure $E^{-1}E = I$ using matrix multiplication. Do this by hand (showing all steps) AND using Python (with the @ operation).

In [ ]:
#You can check your answer here

### 2.2 Inverse of the Row Multiple Elementary Matrix

Remember that the inverse of an elementary matrix has the property that $E^{-1}E = I$ and $EE^{-1}=I$

So if

$E_{3R1} = \begin{bmatrix}
1 & 0 & 0\\
0 & 3 & 0 \\
0 & 0 & 1
\end{bmatrix}$

Then in order to recover the inverse matrix, we need to divide the middle row by three, $$ \frac{1}{3}\text{R}_1 \rightarrow \text{R}_1 $$ which we can do by applying the following elementary matrix

$E_{3R1}^{-1} = \begin{bmatrix}
1 & 0 & 0\\
0 & \frac{1}{3} & 0 \\
0 & 0 & 1
\end{bmatrix}$

So the inverse is the same as the original $E$ except the non-one diagonal entry is the reciprical of the original entry.



In [ ]:
#Using Python
#original
I = np.identity(3)
E = np.copy(I)
E[1,:] = 3*E[1,:]
print('E=')
print(E)

#inverse
Einv = np.copy(I)
Einv[1,:] = (1/3)*Einv[1,:]
print('Einv=')
print(Einv)

#check it
print("EinvE")
print(Einv@E)

E=
[[1. 0. 0.]
 [0. 3. 0.]
 [0. 0. 1.]]
Einv=
[[1.     0.     0.    ]
 [0.     0.3333 0.    ]
 [0.     0.     1.    ]]
EinvE
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### Question 2.2.1 - [2pts]

a.) What is the inverse of the elementary matrix from Question 1.2.1?

In [ ]:
#You can check your answer here
Einv = np.array(

b.) Check to make sure $E^{-1}E = I$ using matrix multiplication. 

If you would like to check your work using Python, use the @ operator for matrix multiplication.

In [ ]:
#You can check your answer here

### 2.3 Inverse of Elementary Matrix that Replaces a row by itself plus multiple of another row

Remember that the inverse of an elementary matrix has the property that $E^{-1}E = I$ and $EE^{-1}=I$

So if

$E_{R2+2*R0} = \begin{bmatrix}
1 & 0 & 0\\
0 & 1 & 0 \\
2 & 0 & 1
\end{bmatrix}$

Then in order to recover the inverse matrix, we need to perform the following row operation:
$$ \text{R}_2 + -2 \text{R}_0 \rightarrow \text{R}_2 $$

So the inverse is the same as $E$ except the off-diagonal entries are the negative of the original.

$E_{R2+2*R0}^{-1} = \begin{bmatrix}
1 & 0 & 0\\
0 & 1 & 0 \\
-2 & 0 & 1
\end{bmatrix}$





In [ ]:
#Using Python
#original
I = np.identity(3)
E = np.copy(I)
E[2,:] = E[2,:]+2*E[0,:]
print(E)

#inverse
Einv = np.copy(I)
Einv[2,:] = Einv[2,:]-2*Einv[0,:]
print('Einv=')
print(Einv)

#check it
print("EinvE")
print(Einv@E)

[[1. 0. 0.]
 [0. 1. 0.]
 [2. 0. 1.]]
Einv=
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [-2.  0.  1.]]
EinvE
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### Question 2.3.1 - [2pts]

a.) What is the inverse of the elementary matrix from Question 1.3.1?

In [ ]:
#You can check your answer here

b.) Check to make sure $E^{-1}E = I$ using matrix multiplication. 

If you would like to check your work using Python, use the @ operator for matrix multiplication.

In [ ]:
#You can check your answer here

## 3. Upper and Lower Triangular Matrices

### 3.1 Upper Triangular Matrix

An upper triangular matrix is a matrix whose entries below the diagonal are zero. For example:

$U = \begin{bmatrix}
2 & 1 & 3\\
0 & 7 & 6 \\
0 & 0 & 4
\end{bmatrix}$

Note that an upper triangular matrix is in echelon form!

#### Question 3.1.1 - [1pt]
Make up a 4x4 upper triangular matrix. 

In [ ]:
#you can create an np.array of U here to check your work with later

Suppose a system of equations can be described by $Ax =b$, where $A$ is the coefficient matrix. If $A$ is an upper triangular matrix ($A = U$, so $Ux=b$), then *back substitution* can be used to solve for x.

#### Question 3.1.2 - [4pts]

Use the upper triangular matrix you created in Question 3.1.1.

Let $b = \begin{bmatrix}
1\\
2 \\
3 \\
4
\end{bmatrix}$.

Use back substituion to solve for $\vec{x} = \begin{bmatrix}
x_1\\
x_2 \\
x_3 \\
x_4
\end{bmatrix}$.

Show your work by hand (Hint: Write out your system of equations, solve for $x_4$ first, then substitute into equation above, and so on). 

You may want to check your work by modifying the Python code below

In [ ]:
#Your code here
U = np.array() #Your upper triangular matrix here
x = np.array() #Your x values that you calculated using back substitution
print("b = ")
print(U@x) #Does this equal b?

### 3.2 Lower Triangular Matrix

A lower triangular matrix is a matrix whose entries above the diagonal are zero. For example:

$L = \begin{bmatrix}
3 & 0 & 0\\
-1 & 7 & 0 \\
-2 & 9 & 4
\end{bmatrix}$

#### Question 3.2.1 - [1pt]

Make up a 4x4 lower triangular matrix. Write it down and print it to the screen.

In [ ]:
#you can create an np.array of L here to check your work with later

Suppose a system of equations can be described by $Ax =b$, where $A$ is the coefficient matrix. If $A$ is a lower triangular matrix ($A = L$, so $Lx=b$), then *forward substitution* can be used to solve for x.

#### Question 3.2.2 - [4pts]

Use the lower triangular matrix you created in Question 3.2.1.

Let $b = \begin{bmatrix}
1\\
2 \\
3 \\
4
\end{bmatrix}$.

Use forward substituion to solve for $x = \begin{bmatrix}
x_1\\
x_2 \\
x_3 \\
x_4
\end{bmatrix}$.

Show your work by hand (Hint: Write out your system of equations, solve for $x_1$ first, then substitute into the equation below, and so on.). 

You may want to check your work by modifying the Python code below

In [ ]:
#Your code here
L = np.array() #Your upper triangular matrix here
x = np.array() #Your x values that you calculated using forward substitution
print("b = ")
print(L@x) #Does this equal b?

### 3.3 Unit Lower Triangular Matrix

A lower triangular matrix whose diagonal entries are all ones. For example:

$L = \begin{bmatrix}
1 & 0 & 0\\
5 & 1 & 0 \\
2 & -7 & 1
\end{bmatrix}$

#### Question 3.3.1 - [1pt]
Make up a 4x4 UNIT lower triangular matrix. 

In [ ]:
#

## 4. Use Elementary Matrices to perform Guassian Elimination

We can write the following system of equations as an *augmented matrix*:

> $x_1 + x_2 + 2x_3 = 8 $

> $-x_1 - 2x_2 + 3x_3 = 1 $

> $3x_1 - 7x_2 + 4x_3 = 10 $

We can also create this augmented matrix using Python:

In [ ]:
A = np.array([[1., 1., 2.],  #R0
              [-1., -2., 3.],  #R1
              [3., -7., 4.]]) #R2
print(A)

[[ 1.  1.  2.]
 [-1. -2.  3.]
 [ 3. -7.  4.]]


In [ ]:
b = np.array([[8.], [1.],[10.]])
print(b)

[[ 8.]
 [ 1.]
 [10.]]


In [ ]:
A_b = np.concatenate((A, b), axis = 1)
print(A_b)

[[ 1.  1.  2.  8.]
 [-1. -2.  3.  1.]
 [ 3. -7.  4. 10.]]


Now we can use use elementary matrices to perform forward elimination row operations to get our augmented matrix into echelon form (EF).

The first row operation is completed by multiplying the first elementary matrix on the left side of the augmented matrix:

$E_1[A|b]$

In [ ]:
#R1 + R0 --> R1
E1 = np.array([[1, 0, 0],
              [1, 1, 0],
              [0, 0, 1]])
print(E1@A_b)

[[ 1.  1.  2.  8.]
 [ 0. -1.  5.  9.]
 [ 3. -7.  4. 10.]]


The next row operation is completed by multiplying the second elementary matrix on the left hand side too.
$E_2E_1[A|b]$

In [ ]:
#R2 -3R0 --> R2
E2 = np.array([[1, 0, 0],
              [0, 1, 0],
              [-3, 0, 1]])
print(E2@E1@A_b)

[[  1.   1.   2.   8.]
 [  0.  -1.   5.   9.]
 [  0. -10.  -2. -14.]]


And so on...
$E_3E_2E_1[A|b]$

In [ ]:
#R2 - 10*R1 --> R2
E3 = np.array([[1, 0, 0],
              [0, 1, 0],
              [0, -10, 1]])
print(E3@E2@E1@A_b)

[[   1.    1.    2.    8.]
 [   0.   -1.    5.    9.]
 [   0.    0.  -52. -104.]]


We have acheieved Echelon Form! Now we can solve our system using *back substituion*.

Note that the *coefficient matrix* has been transformed into an *upper triangular matrix*.

$U = E_3E_2E_1A$

Also note that each *elementary matrix* we used is a *unit lower triangular matrix*



Furthermore, the *product* of all the elementary matrices we used is also *unit lower triangular*.

$E_3E_2E_1$ is unit lower triangular:


In [ ]:
print(E3@E2@E1)

[[  1   0   0]
 [  1   1   0]
 [-13 -10   1]]


#### Side note:

Something you might use later...
the REVERSE product of all of the elementary INVERSE matrices $E_3^{-1}E_2^{-1}E_1^{-1}$ is also *unit lower triangular*


In [ ]:
E1inv = np.linalg.inv(E1)
E2inv = np.linalg.inv(E2)
E3inv = np.linalg.inv(E3)
print(E1inv@E2inv@E3inv)

[[ 1.  0.  0.]
 [-1.  1.  0.]
 [ 3. 10.  1.]]


And note how the off-diagonal terms of the matrix we just found compares to our row operations:

$$ \text{R}_1 + 1 \text{R}_0 \rightarrow \text{R}_1 $$

$$ \text{R}_2 -3 \text{R}_0 \rightarrow \text{R}_2 $$

$$ \text{R}_2 -10 \text{R}_1 \rightarrow \text{R}_2 $$

Very similar by a negative sign...interesting... We will not use this yet but it can be very useful if you are interested in the "shortcut" method mentioned later.

#### Question 4.1 - [10pts]

Use Elementary Matrices to perform Forward Elimination on the following system of equations:

> $x_1 - 3x_3 = -2 $

> $3x_1 + x_2 - 2x_3 = 5 $

> $2x_1 + 2x_2 + x_3 = 4 $

Keep track of your work by hand. You may use Python to complete the matrix multiplication first, and you do NOT need to show all matrix multiplication steps for this question.

Remember: STOP when you have reached regular old ECHELON FORM (EF). In other words, when your coefficient matrix is transformed to a upper triangular matrix. (Do NOT go all the way to reduced echelon form.)

In [ ]:
#You can check your answer here

#### Question 4.2 - [6pts]
Use back substituion to solve for $x = \begin{bmatrix}
x_1\\
x_2 \\
x_3
\end{bmatrix}$.

Show your work by hand. (Hint: Write out your system of equations, solve for $x_3$ first, then substitute into equation above, and so on). 

You may want to check your work by modifying the Python code below

In [ ]:
#Your code here
U = np.array() #Your upper triangular matrix here
x = np.array() #Your x values that you calculated using back substitution
print(U@x) #Does this equal to the rightmost column of your EF augmented matrix?

#### Question 4.3 - [1pt]

Are all the elementary matrices you used unit lower triangular matrices? 

In [2]:
#

#### Question 4.4 - [1pt]

Is the product of all the elementary matrices you used a unit lower triangular matrix? 

Keep track of your work by hand. You may use Python to complete the matrix multiplication first, and you do NOT need to show all matrix multiplication steps for this question.

In [ ]:
#You can check your answer here

#### Question 4.5 - [3pts]
Imagine you had needed to use an elementary matrix that switched rows. For example:

$ {R}_1 \leftrightarrow \text{R}_2 $

a.) What is the elementary matrix that represents this row operation?

b.) Is it a unit lower triangular matrix? 

c.) Would the product of your elementary matrices still be a unit lower triangular matrix if you had used this one in addition to those you used in 4.3? (Keep track of your work by hand. You may use Python to complete the matrix multiplication first, and you do NOT need to show all matrix multiplication steps for this question.)


In [ ]:
#You can check your answer here

#### Question 4.6 - [3pts]
Imagine you had kept reducing your augmented matrix to reduced echelon form. You might need to multiply a row by a non-zero number in order to make the pivots = 1.

For example:

$$ 4\text{R}_1 \rightarrow \text{R}_1 $$

a.) What is the elementary matrix that represents this row operation?

b.) Is it a unit lower triangular matrix? 

c.) Would the product of your elementary matrices still be a unit lower triangular matrix if you had used this one in addition to the ones you used in 4.3?
(Keep track of your work on by hand. You may use Python to complete the matrix multiplication first, and you do NOT need to show all matrix multiplication steps for this question.)

In [ ]:
#You can check your answer here

#### Question 4.7 - [3pts]

Imagine you had kept reducing your augmented matrix to reduced echelon form. You would need to perform row operations to get the values above your pivots to be zero. For example you might need to use this row operation:
$$ \text{R}_1 + -7 \text{R}_2 \rightarrow \text{R}_1 $$

a.) Write down / print out the elementary matrix that represents this row operation.

b.) Is it a unit lower triangular matrix? Write down your answer/ print your answer to the screen.

c.) Would the product of your elementary matrices still be a unit lower triangular matrix if you had used this one in addition to the ones you used in 4.3?
(Keep track of your work by hand. You may use Python to complete the matrix multiplication first, and you do NOT need to show all matrix multiplication steps for this question.)

In [ ]:
#You can check your answer here

## 5. LU Decomposition

We can represent our system of equations as

$$Ax=b,$$

where $A$ is the coeffient matrix, $x$ is the column vector of our solutions, and $b$ is the column vector of constants.

If we can rewrite (or "decompose") $A$ as a product of a lower triangular matrix and an upper triangular matrix such that $$A = LU,$$

then
$$Ax=b$$ 
becomes
$$LUx=b.$$

If we let $Ux=y$, then we can write this as

$$Ly=b$$

and we can use *forward substituion* to solve for $y$ (Shown in Question 10).

But we still need to solve for $x$.

Well, we defined
$$Ux=y$$

and we can use *back substition* to get x. (Shown in Question 8).

Now we have solved our system of equations using an LU Decomposition!

Here is a [video](https://www.youtube.com/watch?v=o5viKb1jqhM&list=PLkZjai-2Jcxlg-Z1roB0pUwFU-P58tvOx&index=16) in case you find it helpful

### 5.1 Solving a system using LU Decomposition when given L and U

#### Question 5.1.1 - [10pts] 

Following the procedure outlined above, complete the following question:

<img src="https://lh3.googleusercontent.com/pw/ADCreHfIIgkxnJrIRLPFTrXa_WgAWIwM0xQ6WBb9yFoFKSQSfzC-5XBNjS6AopTaLB4qrHv-rPANNoNnstrn0uGN34_K0PwZkydmfP_1wm6njIG00-DzJGZg7qgsK-Tf_HeuffW3lBOodIThquOyLqfi2xSe=w879-h331-s-no-gm?authuser=0" width="550">

Do your work by hand. You may want to check your work with Python


In [ ]:
#You can check your answer here

#### Question 5.1.2 - [10pts] 
Following the procedure outlined above, complete the following question:

<img src="https://lh3.googleusercontent.com/pw/ADCreHfIba9roqnB86QDbM42xASE_tVjECAWnUjOKF-G5tKaMeSirYC6iYu9CtUJa-4BNrr5JwQ65Xd5DfG0oeE_8EF1-ln-6aJJFCgT0zW9o8crcIDrH1P6GF0oeZfSn1-bvqi7Q_oN9Wkxe_2zaZdqdRiK=w894-h417-s-no-gm?authuser=0" width="550">



Do your work by hand. You may want to check your work with Python

In [ ]:
#You can check your answer here

But what if we are not given $L$ and $U$?

### 5.2 How do we find a L and U for the decomposition?

This method only works if $A$ is *row equivalent* to an *upper diagonal matrix*. This means that by multiplying $A$ on the left by elementary matrices, we can produce an upper diagonal matrix.

$$U = E_k E_{k-1}...E_2E_1A$$

Furthermore, the elementary matrices used can NOT contain a row switch.

So that helps us find $U$, but how do we find $L$?

Let's take the equation above and start applying the inverse elementary matrices.

So first we multiply both sides by $E_k^{-1}$

$$E_k^{-1}U = E_k^{-1}E_k E_{k-1} ...E_2E_1A$$

But remember $E_k^{-1}E_k = I$ so

$$E_k^{-1}U = I E_{k-1} ...E_2E_1A$$
$$E_k^{-1}U = E_{k-1} ...E_2E_1A$$

If we keep applying the inverses...
$$E_1^{-1}E_2^{-1}...E_{k-1}^{-1}E_k^{-1}U = A$$

Where $$E_1^{-1}E_2^{-1}...E_{k-1}^{-1}E_k^{-1} = L,$$ a unit lower diagonal matrix.

We showed that $E_k E_{k-1}...E_2E_1$ would be unit lower diagonal if they converted a coefficient matrix to an upper diagonal matrix without a row switch (Questions 12-18). It follows that $E_1^{-1}E_2^{-1}...E_{k-1}^{-1}E_k^{-1}$ is also unit lower diagonal (See Questions 4-6).

Here are some videos in case you find them helpful:

[Video 1](https://www.youtube.com/watch?v=j48z_nY-oB8&list=PLkZjai-2Jcxlg-Z1roB0pUwFU-P58tvOx&index=15)

[Video 2](https://www.youtube.com/watch?v=-eA2D_rIcNA)



#### Question 5.2.1 - [10pts] 

Following the procedure outlined above, complete the following question:

<img src="https://lh3.googleusercontent.com/pw/ADCreHfvZ2rXvm_2faqFZAWZrWYGTEZnPLcHFlD7eFLQI7rDNdjGQj_lkKfwNo-bMocxzAJ_Yqql6Hqn3ze51npNAxePq0HhOFtHvGcXH8Maf9ZSkdyIKjdsjnzDCZL8fzjLajJISwAO0PtNPSmAXD6Gzgq1=w538-h192-s-no-gm?authuser=0" width="550">

Do your work by hand. You may want to check your work with Python



In [ ]:
#You can check your answer here

#### Question 5.2.2 - [10pts] 

zyBook Additional Exercise 20.8.2b

Find the LU Decomposition of the given matrix

<img src="https://lh3.googleusercontent.com/pw/ADCreHdpXUjEYKXSawNrVz6zonInRaTZL3LS42avusDZlbu1j74a7_yzZtoHWvm4LS7zLh7G0S14za3NW751qAzCK3yk6atTtqC5LmlFbbAW0FAikZxuE9MC4QaLIvEb59fRXJ8XAugp2jGE5pogKnP7I6u_=w391-h154-s-no-gm?authuser=0" width="550">

Complete your work by hand. You may want to check your work with Python

In [ ]:
#You can check your answer here

### 5.3 Putting it all together

#### Question 5.3.1 - [10pts] 

<img src="https://lh3.googleusercontent.com/pw/ADCreHc1hinnT5dtPhw0a4WVzaHNqJBpHEApPeBAviHvpjjHMlGTwAAuleWCabxyA9rdqvSTJ21VoroEIzU2KuFV6O9g1_3spBC28B72FaqqpzERyNhv6BisEx4vNRRG5IHubT8Xl1N6oNfeQTYUrrI8DNHe=w784-h147-s-no-gm?authuser=0" width="550">

Complete your work by hand. You may want to check your work with Python


In [ ]:
#You can check your answer here

### 5.4 "Shortcut" method
If you look on the internet you will find folks talking about the "shortcut method". I want to see your work to find L and U the "long" way, as explained above and as explained in the zyBook, but if it helps you to also know the "shortcut" you can find it at links like [these](https://www.youtube.com/watch?v=UlWcofkUDDU)

If it confuses you, just ignore it!

### 5.5 PLU Decomposition
You can extend this analysis to be able to account for row switches by decomposing $A$ as $A=PLU$, where $P$ is a "permutation" matrix that accounts for the row switching. This is not covered in the zyBook.

There are many [resources online](https://www.youtube.com/watch?v=E3cCRcdFGmE) if you are curious!
