In [ ]:
import numpy as np
np.set_printoptions(precision=4,suppress=True)

# Echelon Form (EF)

* any zero rows below all nonzero rows
* leading entry (first non-zero element) of each row is to the right of leading entries in rows above
* The entries below a leading entry are zero.

This is sometimes also called Row Echelon Form.

Are the matrices below in Echelon Form?

In [ ]:
A = np.array([[3., 4., 8., 4.], 
              [0., 5., 7., 9.], 
              [0., 0., 3., 2.]]) 

[[3. 4. 8. 4.]
 [0. 5. 7. 9.]
 [0. 0. 3. 2.]]


The matrix above is in echelon form

In [ ]:
A = np.array([[3., 4., 8., 4., 8.],  
              [0., 5., 7., 9., 9.],  
              [0., 0., 0., 2., 1.]]) 
print(A)

[[3. 4. 8. 4. 8.]
 [0. 5. 7. 9. 9.]
 [0. 0. 0. 2. 1.]]


The matrix above is in echelon form

In [ ]:
A = np.array([[0., 4., 8., 4.], # leading entry in top row is to the right of leading entry below it
              [5., 5., 7., 9.],
              [0., 0., 0., 2.]])
print(A)

[[0. 4. 8. 4.]
 [5. 5. 7. 9.]
 [0. 0. 0. 2.]]


The matrix above is NOT in echelon form

# Pivots & Pivot Columns, Basic Variables & Free Variables

* **Pivot** - Leading entry in a matrix that is in echelon form
* **Pivot Column** - Column that contains a pivot of a matrix in echelon form
* **Basic Variable** - Variable represented by a pivot column
* **Free Variable** - Variable represented by non-pivot column (If a a solution exists, a free variable indicates that there are infinite solutions)

In [ ]:
A = np.array([[3., 4., 8., 4.], #3 is pivot
              [0., 5., 7., 9.], #5 is pivot
              [0., 0., 3., 2.]]) #3 is pivot
print(A)

[[3. 4. 8. 4.]
 [0. 5. 7. 9.]
 [0. 0. 3. 2.]]


In [ ]:
            #  x1  x2  x3  x4 
A = np.array([[3., 4., 8., 4., 8.],  #3 is pivot
              [0., 5., 7., 9., 9.],  #5 is pivot, x3 is a free variable
              [0., 0., 0., 2., 1.]]) #2 is pivot
print(A)

[[3. 4. 8. 4. 8.]
 [0. 5. 7. 9. 9.]
 [0. 0. 0. 2. 1.]]


# Existence

If a solution exists - system is **consistent**

If a solution does not exist - system is **inconsistent**

*How to tell: A matrix in EF whose last column is a pivot column has no solution.*

In [ ]:
#An example of a matrix with no solution
A = np.array([[3., 2., -1., -4.],
              [0., 0., 0., -6.]]) #-6 is a pivot in the last column
print(A)
#last row has illegal math! 0*x1+0*x2+0*x3=0, not 6

[[ 3.  2. -1. -4.]
 [ 0.  0.  0. -6.]]


# Uniqueness

If one solution exists - there is a **unique** solution

If infinite solutions exist - the solution is **non-unique**

*How to tell: A matrix in EF with a free variable whose last column is not a pivot column has infinitely many solutions.*

In [ ]:
A = np.array([[1., 0., 0., 3.],
              [0., 0., 1., -6.], #x2 is a free variable, associated with infinite solutions
              [0., 0., 0., 0.]]) #last column not a pivot column, so solution does exist
print(A)

[[ 1.  0.  0.  3.]
 [ 0.  0.  1. -6.]
 [ 0.  0.  0.  0.]]


# Reduced Echelon Form (REF)
* Any rows that contain all zeros are below all nonzero rows.
* The leading entry of each row is to the right of the leading terms in the rows above.
* All the entries below a leading entry are zeros.
* The leading entry for each nonzero row is 1.
* Each leading entry of 1 has zeros above. That is, the leading ones are the only nonzero entry in that column.

This is also sometimes called Reduced *Row* Echelon Form

Are the matrices below in REDUCED Echelon Form?

In [ ]:
A = np.array([[3., 4., 8., 4., 8.],
              [0., 5., 7., 9., 9.],
              [0., 0., 0., 2., 1.]])
print(A)

[[3. 4. 8. 4. 8.]
 [0. 5. 7. 9. 9.]
 [0. 0. 0. 2. 1.]]


No, the matrix above is in echelon form, but not reduced echelon form.

In [ ]:
A = np.array([[1., 0., 0., 8.],
              [0., 1., 0., 9.],
              [0., 0., 1., 1.]])
print(A)

[[1. 0. 0. 8.]
 [0. 1. 0. 9.]
 [0. 0. 1. 1.]]


Yes the matrix above is in reduced echelon form

In [ ]:
A = np.array([[1., 2., 0.,  0., 0., 2.,  3.],
              [0., 0., 1.,  3., 0. ,2.,  1.],
              [0., 0., 0.,  0., 1., 1., -3.],
              [0., 0., 0.,  0., 0., 0.,  0. ]])
print(A)

[[ 1.  2.  0.  0.  0.  2.  3.]
 [ 0.  0.  1.  3.  0.  2.  1.]
 [ 0.  0.  0.  0.  1.  1. -3.]
 [ 0.  0.  0.  0.  0.  0.  0.]]


Yes the matrix above is in reduced echelon form

Describe the existance and uniqueness of the solution of the system of equations represented by the following matrix:

In [ ]:
A = np.array([[1., 0., 0., 0.],
              [0., 1., 0., 5.],
              [0., 0., 1., 2.]])
print(A)

[[1. 0. 0. 0.]
 [0. 1. 0. 5.]
 [0. 0. 1. 2.]]


Echelon Form?

Reduced Echelon Form?

Does the solution Exist?

Is the solution Unique?


REF, unique solution exists

How about this one?

In [ ]:
A = np.array([[1, 0, 0, 0],  #R0
              [0, 1, 0, 5],  #R1
              [0, 0, 0, 1]]) #R2
print(A)

[[1 0 0 0]
 [0 1 0 5]
 [0 0 0 1]]


Echelon Form?

Reduced Echelon Form?

Does the solution Exist?

Is the solution Unique?

EF (not fully reduced because non-zero value above pivot in last column), but we can already see no solution exists because of the "illegal" math in the last column:

$0x_3$ = 1 <-- illegal math! Zero is not 1!

In [ ]:
# Side note: We can fully reduce this using one more row operation
# R1 - 5*R2 --> R1
A[1,:] = A[1,:] - 5*A[2,:]
print(A)
#Solution is still "inconsistent"

[[1 0 0 0]
 [0 1 0 0]
 [0 0 0 1]]


How about this one?

In [ ]:
A = np.array([[1, 0, 0, 0],
              [0, 1, 1, 5],
              [0, 0, 0, 0]])
print(A)

[[1 0 0 0]
 [0 1 1 5]
 [0 0 0 0]]


Echelon Form?

Reduced Echelon Form?

Does the solution Exist?

Is the solution Unique?

REF, infinite (non-unique) solutions exist

In [ ]:
A = np.array([[1, 0, 0, 0],
              [0, 1, 1, 5],  #x3 is a free variable
              [0, 0, 0, 0]]) #last column is not a pivot column

# Gaussian Elimination

Steps to solve (or identify an unsolvable) solution - works for any system!

## Part 1: Forward Elimation to acheive Echelon Form
1.   Find leading entry of the first column
2.   If leading entry is not in first row, swap rows to get it to the top row
3.   perform elementary row operations using top row leading entry to make all entries below it zero
4.   Repeat steps 1-3 for sub-matrix containing all entries to the right and below of upper leading entry you just worked with
5. Stop when matrix is in ECHELON FORM

## Part 2: Back-substitution
1. Matrix is now in Echelon Form
2. Solve last equation for basic variable. If system contains free variables write basic variable in terms of free variable
3. Substitute value (or expression) for the variable into the equation above to obtain solution for different variable
4. Repeat until unique value or expression is found for all variables

# Gauss-Jordan Elimination

Steps to solve (or identify an unsolvable) solution - works for any system!

1. same forward elimination as Gaussian *(see above section on Guassian Elimination- Part 1: Forward Elimination to acheive Echelon Form)*
2. make all pivots 1 by multiplying row by reciprical of pivot
3. perform elementary row operations using rightmost pivot to make all entries above it zero
4. repeat step 3 for sub-matrix containing all entries above and to the left of pivot you just worked off of
5. stop when entries above all pivots are zero

Your matrix is now in REDUCED row echelon form!