# Echelon Forms and Characterizing Solutions to Systems of Equations

In [ ]:
import numpy as np
np.set_printoptions(precision=4,suppress=True)

## Echelon Form (EF)

* any zero rows below all nonzero rows
* leading entry (first non-zero element) of each row is to the right of leading entries in rows above
* The entries below a leading entry are zero.

This is sometimes also called Row Echelon Form.

*NOTE: A matrix can have many different echelon forms depending on how you do your row operations. The **locations** of the leading entries will be the same between forms, but the numbers in the matrix can be different.*

Are the matrices below in Echelon Form?

In [ ]:
Ab = np.array([[3., 4., 8., 4.], 
              [0., 5., 7., 9.], 
              [0., 0., 3., 2.]])
print(Ab) 

[[3. 4. 8. 4.]
 [0. 5. 7. 9.]
 [0. 0. 3. 2.]]


The matrix above is in echelon form

In [ ]:
Ab = np.array([[3., 4., 8., 4., 8.],  
              [0., 5., 7., 9., 9.],  
              [0., 0., 0., 2., 1.]]) 
print(Ab)

[[3. 4. 8. 4. 8.]
 [0. 5. 7. 9. 9.]
 [0. 0. 0. 2. 1.]]


The matrix above is in echelon form

In [ ]:
Ab = np.array([[0., 4., 8., 4.], # leading entry in top row is to the right of leading entry below it
              [5., 5., 7., 9.],
              [0., 0., 0., 2.]])
print(Ab)

[[0. 4. 8. 4.]
 [5. 5. 7. 9.]
 [0. 0. 0. 2.]]


The matrix above is NOT in echelon form

### Gaussian Elimination

Steps to solve (or identify an unsolvable) solution - works for any system!

#### Part 1: Forward Elimation to acheive Echelon Form
1.   Find leading entry of the first column
2.   If leading entry is not in first row, swap rows to get it to the top row
3.   Perform elementary row operations using top row leading entry to make all entries below it zero
4.   Repeat steps 1-3 for sub-matrix containing all entries to the right and below of upper leading entry you just worked with
5. Stop when matrix is in ECHELON FORM

#### Part 2: Back-substitution
1. Matrix is now in Echelon Form
2. Solve last equation for basic variable. If system contains free variables write basic variable in terms of free variable
3. Substitute value (or expression) for the variable into the equation above to obtain solution for different variable
4. Repeat until unique value or expression is found for all variables

## Reduced Echelon Form (REF)
* Any rows that contain all zeros are below all nonzero rows.
* The leading entry of each row is to the right of the leading terms in the rows above.
* All the entries below a leading entry are zeros.
* The leading entry for each nonzero row is 1.
* Each leading entry of 1 has zeros above. That is, the leading ones are the only nonzero entry in that column.

This is also sometimes called Reduced *Row* Echelon Form

*NOTE: A matrix only has **one** REDUCED echelon form!* 

Are the matrices below in REDUCED Echelon Form?

In [ ]:
Ab = np.array([[3., 4., 8., 4., 8.],
              [0., 5., 7., 9., 9.],
              [0., 0., 0., 2., 1.]])
print(Ab)

[[3. 4. 8. 4. 8.]
 [0. 5. 7. 9. 9.]
 [0. 0. 0. 2. 1.]]


No, the matrix above is in echelon form, but not reduced echelon form.

In [ ]:
Ab = np.array([[1., 0., 0., 8.],
              [0., 1., 0., 9.],
              [0., 0., 1., 1.]])
print(Ab)

[[1. 0. 0. 8.]
 [0. 1. 0. 9.]
 [0. 0. 1. 1.]]


Yes the matrix above is in reduced echelon form

In [ ]:
Ab = np.array([[1., 2., 0.,  0., 0., 2.,  3.],
              [0., 0., 1.,  3., 0. ,2.,  1.],
              [0., 0., 0.,  0., 1., 1., -3.],
              [0., 0., 0.,  0., 0., 0.,  0. ]])
print(Ab)

[[ 1.  2.  0.  0.  0.  2.  3.]
 [ 0.  0.  1.  3.  0.  2.  1.]
 [ 0.  0.  0.  0.  1.  1. -3.]
 [ 0.  0.  0.  0.  0.  0.  0.]]


Yes the matrix above is in reduced echelon form

### Gauss-Jordan Elimination

Steps to solve (or identify an unsolvable) solution - works for any system!

1. Same forward elimination as Gaussian *(see above section on Guassian Elimination- Part 1: Forward Elimination to acheive Echelon Form)*
2. Make all pivots 1 by multiplying row by reciprical of pivot
3. Perform elementary row operations using rightmost pivot to make all entries above it zero
4. Repeat step 3 for sub-matrix containing all entries above and to the left of pivot you just worked off of
5. Stop when entries above all pivots are zero

Your matrix is now in REDUCED row echelon form!

## Pivots & Pivot Columns, Basic Variables & Free Variables

* **Pivot** - Leading entry in a matrix that is in echelon form
* **Pivot Column** - Column that contains a pivot of a matrix in echelon form
* **Basic Variable** - Variable represented by a pivot column
* **Free Variable** - Variable represented by non-pivot column (If a a solution exists, a free variable indicates that there are infinite solutions)

In [ ]:
Ab = np.array([[3., 4., 8., 4.], #3 is pivot
              [0., 5., 7., 9.], #5 is pivot
              [0., 0., 3., 2.]]) #3 is pivot
print(Ab)

[[3. 4. 8. 4.]
 [0. 5. 7. 9.]
 [0. 0. 3. 2.]]


In [ ]:
            #  x1  x2  x3  x4 
Ab = np.array([[3., 4., 8., 4., 8.],  #3 is pivot
              [0., 5., 7., 9., 9.],  #5 is pivot, x3 is a free variable
              [0., 0., 0., 2., 1.]]) #2 is pivot
print(Ab)

[[3. 4. 8. 4. 8.]
 [0. 5. 7. 9. 9.]
 [0. 0. 0. 2. 1.]]


## Characterizing the Solution

### Existence

If a solution exists - system is **consistent**

If a solution does not exist - system is **inconsistent**

*How to tell: A matrix in EF whose last column is a pivot column has no solution.*

In [ ]:
#An example of a matrix with no solution
Ab = np.array([[3., 2., -1., -4.],
              [0., 0., 0., -6.]]) #-6 is a pivot in the last column
print(Ab)
#last row has illegal math! 0*x1+0*x2+0*x3=0, not 6

[[ 3.  2. -1. -4.]
 [ 0.  0.  0. -6.]]


### Uniqueness

If one solution exists - there is a **unique** solution

If infinite solutions exist - the solution is **non-unique**

*How to tell: A matrix in EF with a free variable whose last column is not a pivot column has infinitely many solutions.*

In [ ]:
Ab = np.array([[1., 0., 0., 3.],
              [0., 0., 1., -6.], #x2 is a free variable, associated with infinite solutions
              [0., 0., 0., 0.]]) #last column not a pivot column, so solution does exist
print(Ab)

[[ 1.  0.  0.  3.]
 [ 0.  0.  1. -6.]
 [ 0.  0.  0.  0.]]


### Rank

The rank of a matrix is the number of NON-ZERO ROWS in an ECHELON FORM of that matrix

The rank of matrix M is denoted: $r(M)$

The rank of the COEFFICIENT matrix $r(A)$ tells us the number of BASIC VARIABLES!

### Nullity

The nullity is the number of COLUMNS in the matrix, *MINUS* the RANK of the matrix.

The nullity of matrix M is denoted: $n - r(M)$

The nullity of the COEFFICIENT matrix $n- r(A)$ tell us the number of FREE VARIABLES!

### Solvability

<img src="rank.png" width="400">

### Examples

Describe the existance and uniqueness of the solution of the system of equations represented by the following matrix:

In [ ]:
Ab = np.array([[1., 0., 0., 0.],
              [0., 1., 0., 5.],
              [0., 0., 1., 2.]])
print(Ab)

[[1. 0. 0. 0.]
 [0. 1. 0. 5.]
 [0. 0. 1. 2.]]


Echelon Form?

Reduced Echelon Form?

What is the number of unknowns, n? (Columns in A)

What is the rank of A?

What is the rank of Ab?

Does the solution Exist?

Is the solution Unique?


REF, n = 3, r(A)=3, r([A|b])=3, unique solution exists

How about this one?

In [ ]:
Ab = np.array([[1, 0, 0, 0],  #R0
              [0, 1, 0, 5],  #R1
              [0, 0, 0, 1]]) #R2
print(Ab)

[[1 0 0 0]
 [0 1 0 5]
 [0 0 0 1]]


Echelon Form?

Reduced Echelon Form?

Does the solution Exist?

Is the solution Unique?

EF (not fully reduced because non-zero value above pivot in last column), but we can already see no solution exists because of the "illegal" math in the last column:

$0x_3$ = 1 <-- illegal math! Zero is not 1!

We can fully reduce this using one more row operation:

In [ ]:
# R1 - 5*R2 --> R1
Ab[1,:] = Ab[1,:] - 5*Ab[2,:]
print(Ab)
#Solution is still "inconsistent"

[[1 0 0 0]
 [0 1 0 0]
 [0 0 0 1]]


What is the number of unknowns, n? (Columns in A)

What is the rank of A?

What is the rank of Ab?

REF, n = 3, r(A)=2, r([A|b])=3

How about this one?

In [ ]:
Ab = np.array([[1, 0, 0, 0],
              [0, 1, 1, 5],
              [0, 0, 0, 0]])
print(Ab)

[[1 0 0 0]
 [0 1 1 5]
 [0 0 0 0]]


Echelon Form?

Reduced Echelon Form?

What is the number of unknowns, n? (Columns in A)

What is the rank of A?

What is the rank of Ab?

Does the solution Exist?

Is the solution Unique?

REF, n=3, r(A)=2, r([A|b])=2, infinite (non-unique) solutions exist

In [ ]:
Ab = np.array([[1, 0, 0, 0],
              [0, 1, 1, 5],  #x3 is a free variable
              [0, 0, 0, 0]]) #last column is not a pivot column

Nullity of A above = n - r(A) 

= 3 - 2 

= 1

So there is 1 free variable

## Finding the solution set for infinite solutions

Just because there are infinite solutions, doesn't mean any old set of numbers will solve the equations...

When we write the solution set for a system of infinite solutions we write the solution for the *basic variables in terms of the free variables*:

In [ ]:
Ab = np.array([[1, 0, 0, 0],
              [0, 1, 1, 5],  #x3 is a free variable
              [0, 0, 0, 0]]) #last column is not a pivot column

So we can rewrite the augmented matrix above as:

$x_1=0$

$x_2 + x_3 = 5$

Where $x_1$ and $x_2$ are basic variables and $x_3$ is a free variable. So we need to solve for $x_1$ and $x_2$ in terms of $x_3$.

So $x_2 = 5-x_3$,

and $x_1$ doesn't depend on $x_3$ at all, so it just stays $x_1=0$.

The final solution set is:
$x = \begin{bmatrix}
0 \\
5-x_3\\
x_3\\
\end{bmatrix}$.