In [316]:
import numpy as np
np.set_printoptions(precision=4,suppress=True)

# Elimination Methods for Systems of Equations with a Unique Solution

For example, suppose you have the following system of equations:

$x_2 + 2x_3 = 2$

$2x_1 + 2x_2 + x_3 = 8$

$4x_1 + 2x_2 + 6x_3 = 4$

We can rewrite this system of equations as:

$Ax = b$

where $A$ is the coefficient matrix, $x$ is a column vector of the solutions, and $b$ is a column vector of the constants on the right hand side.

The associated coefficient matrix A is:

In [317]:
A = np.array([[0,1,2],
              [2,2,1],
              [4,2,6]],dtype=float)
print(A)

[[0. 1. 2.]
 [2. 2. 1.]
 [4. 2. 6.]]


The associated column vector of constants (for the right hand side of the system of equations) is:

In [318]:
b = np.array([[2],
              [8],
              [4]],dtype=float)
print(b)

[[2.]
 [8.]
 [4.]]


# Gaussian Elimination

Algorithm (recipe of prescribed steps) to solve system of linear equations. The algorithm has two parts.

## Part 1: Forward Elimation to acheive Upper Triangular Form

### Part 1 Step a.) Creating the Augmented Matrix [A|b]:


In [319]:
A_b = np.concatenate((A, b), axis = 1)
print('Augmented matrix:\n', A_b)

Augmented matrix:
 [[0. 1. 2. 2.]
 [2. 2. 1. 8.]
 [4. 2. 6. 4.]]


### Part 1 Step b.) Find leading entry of the first column

In [320]:
# Find first non-zero entry in column zero of A_b
print("Upper left entry is zero:",A_b[0,0]) #row 0, column 0
print("Middle left entry is non-zero:", A_b[1,0]) #row 1, column 0

Upper left entry is zero: 0.0
Middle left entry is non-zero: 2.0


### Part 1 Step c.) If leading entry is not in first row, swap rows to get it to the top row



In [321]:
# R0 <--> R1
R0 = np.copy(A_b[0,:]) #make a copy of row 0
R1 = np.copy(A_b[1,:]) #make a copy of row 1
A_b[1,:] = R0 #put the copy of old row 0 in row 1
A_b[0,:] = R1 #put the copy of old row 1 in row 0 
print(A_b)

[[2. 2. 1. 8.]
 [0. 1. 2. 2.]
 [4. 2. 6. 4.]]


### Part 1 Step d.) Perform elementary row operations using top row leading entry (also known as the "pivot") to make all entries below it zero

In [322]:
# -2*R0 + R2  --> R2
A_b[2,:] = - 2*A_b[0,:] + A_b[2,:]
print(A_b)

[[  2.   2.   1.   8.]
 [  0.   1.   2.   2.]
 [  0.  -2.   4. -12.]]


### Part 1 Step e.) Repeat previous steps for sub-matrix containing all entries to the right and below of upper leading entry you just worked with

In [323]:
# 2*R1 + R2  --> R2
A_b[2,:] = 2*A_b[1,:] + A_b[2,:]
print(A_b)

[[ 2.  2.  1.  8.]
 [ 0.  1.  2.  2.]
 [ 0.  0.  8. -8.]]


### Part 1 Step f.) Stop when the *coefficient matrix* is in Upper Triangular Form

We are already there!

## Part 2: Back-substitution

### Part 2 Step a.)  Rewrite our system of equations from the manipulated augmented matrix above:


$2x_1 + 2x_2 + x_3 = 8$

$1x_2 + 2x_3 = 2$

$8x_3 = -8$


### Part 2 Step b.) Solve for the variable in the bottom equation

Remember this is our system of equations:

$2x_1 + 2x_2 + x_3 = 8$

$1x_2 + 2x_3 = 2$

$8x_3 = -8$

so looking at the bottom equation:

 $8x_3 = -8$     
   
>$x_3 = -8/8$

>$x_3 = -1$

In [324]:
x3 = -8/8
print(x3)

-1.0


### Part 2 Step c.) Use *backsubstitution* to solve for the unknown variable in the next row up
Remember this is our system of equations:

$2x_1 + 2x_2 + x_3 = 8$

$1x_2 + 2x_3 = 2$

$8x_3 = -8$

Plug the variable you just found ($x_3 = -1$) into the equation representing the row above (this is called "backsubstitution")


Row above:

$1x_2 + 2x_3 = 2$

backsubstitute using $x_3 = -1$:

$x_2 + 2(-1) = 2$

and solve for the remaining variable

$x_2 = 2 - 2(-1)$

> $x_2 = 2 + 2$ 

> $x_2 = 4$



In [325]:
x2 = 2 - 2*x3
print(x2)

4.0


### Part 2 Step d.) Continue backsubstitution until all variables have been solved for.

Remember this is our system of equations:

$2x_1 + 2x_2 + x_3 = 8$

$1x_2 + 2x_3 = 2$

$8x_3 = -8$

Just have $x_1$ left to solve for and we already know $x_2$ and $x_3$...

$2x_1 + 2x_2 + x_3 = 8$

$2x_1 + 2(4) + (-1) = 8$

$2x_1 +  = 8 - 2(4) - (-1)$

$x_1 = (8 - 2(4) - (-1))/2$


In [326]:
x1 = (8-2*x2 - x3)/2
print(x1)

0.5


### We have solved our system of equations and found the unique solution!


$x = \begin{bmatrix}
\frac{1}{2} \\
4\\
-1\\
\end{bmatrix}$.

-------------------------------------------------------------------------------------------


# Gauss-Jordan Elimination

The algorithm for Gauss-Jordan Elimination is similar but different.  It has three parts.

## Part 1: Forward Elimination, is the same as Guassian Elimination

Say we start with the same system of equations:

$x_2 + 2x_3 = 2$

$2x_1 + 2x_2 + x_3 = 8$

$4x_1 + 2x_2 + 6x_3 = 4$

So perform the same steps as in the forward elimination of Guassian Elimination:

In [327]:
#coefficient matrix
A = np.array([[0,1,2],
              [2,2,1],
              [4,2,6]],dtype=float)
print('Coefficient Matrix:\n',A)
print() # space output to be more readable

# column vector of constants
b = np.array([[2],
              [8],
              [4]],dtype=float)
print('Column vector of constants:\n',b)
print() # space output to be more readable

# augmented matrix
A_b = np.concatenate((A, b), axis = 1)
# print matrix and the next step you will take
print('Augmented matrix:\n', A_b,"Next Row Operation: R0<--> R1")
print() # space output to be more readable

# Row Operation: R0 <--> R1
R0 = np.copy(A_b[0,:]) #make a copy of row 0
R1 = np.copy(A_b[1,:]) #make a copy of row 1
A_b[1,:] = R0 #put the copy of old row 0 in row 1
A_b[0,:] = R1 #put the copy of old row 1 in row 0 
print("Result of Row Operation")
# print matrix and the next step you will take
print(A_b,"Next Row Operation: -2*R0 + R2  --> R2")
print() # space output to be more readable

# Row Operation: -2*R0 + R2  --> R2
A_b[2,:] = - 2*A_b[0,:] + A_b[2,:]
print("Result of Row Operation")
# print matrix and the next step you will take
print(A_b,"Next Row Operation: 2*R1 + R2  --> R2")
print() # space output to be more readable

# Row Operation: 2*R1 + R2  --> R2
print("Result of Row Operation")
A_b[2,:] = 2*A_b[1,:] + A_b[2,:]
print(A_b, "Coefficient Matrix in Upper Triangular Form- Yay! Step 1 complete")

Coefficient Matrix:
 [[0. 1. 2.]
 [2. 2. 1.]
 [4. 2. 6.]]

Column vector of constants:
 [[2.]
 [8.]
 [4.]]

Augmented matrix:
 [[0. 1. 2. 2.]
 [2. 2. 1. 8.]
 [4. 2. 6. 4.]] Next Row Operation: R0<--> R1

Result of Row Operation
[[2. 2. 1. 8.]
 [0. 1. 2. 2.]
 [4. 2. 6. 4.]] Next Row Operation: -2*R0 + R2  --> R2

Result of Row Operation
[[  2.   2.   1.   8.]
 [  0.   1.   2.   2.]
 [  0.  -2.   4. -12.]] Next Row Operation: 2*R1 + R2  --> R2

Result of Row Operation
[[ 2.  2.  1.  8.]
 [ 0.  1.  2.  2.]
 [ 0.  0.  8. -8.]] Coefficient Matrix in Upper Triangular Form- Yay! Step 1 complete


## Part 2: Scale each row so that all elements on the coefficient matrix diagonal are 1

Use more row operations to make all the elements on the coefficient matrix diagonal 1 

In [328]:
print(A_b,"Next Row Operation: (1/2)*R0 --> R0")
print()

# Row Operation: (1/2)*R0 --> R0
print("Result of Row Operation")
A_b[0,:] = (1/2)*A_b[0,:]
print(A_b, "Next Row Operation: (1/8)*R2 --> R2")
print()

# Row Operation: (1/8)*R2 --> R2
print("Result of Row Operation")
A_b[2,:] = (1/8)*A_b[2,:]
print(A_b, "All coffiecient matrix diagonal entries are now 1! Move onto Part 3!")

[[ 2.  2.  1.  8.]
 [ 0.  1.  2.  2.]
 [ 0.  0.  8. -8.]] Next Row Operation: (1/2)*R0 --> R0

Result of Row Operation
[[ 1.   1.   0.5  4. ]
 [ 0.   1.   2.   2. ]
 [ 0.   0.   8.  -8. ]] Next Row Operation: (1/8)*R2 --> R2

Result of Row Operation
[[ 1.   1.   0.5  4. ]
 [ 0.   1.   2.   2. ]
 [ 0.   0.   1.  -1. ]] All coffiecient matrix diagonal entries are now 1! Move onto Part 3!


## Part 3: Perform Backward Elimination 

### Part 3 Step a.) 

Perform elementary row operations to make all entries above the diagonal zero. *Start with the right-most column of the **coefficient** matrix.*



In [329]:
print(A_b,"Next Row Operation: -2*R2 + R1--> R1")
print()

# Row Operation: -2*R2 + R1--> R1
print("Result of Row Operation")
A_b[1,:] = -2*A_b[2,:]+ A_b[1,:]
print(A_b, "Next Row Operation: -(1/2)*R2 + R0--> R0")
print()

print("Result of Row Operation")
A_b[0,:] = -(1/2)*A_b[2,:]+ A_b[0,:]
print(A_b)
print()


[[ 1.   1.   0.5  4. ]
 [ 0.   1.   2.   2. ]
 [ 0.   0.   1.  -1. ]] Next Row Operation: -2*R2 + R1--> R1

Result of Row Operation
[[ 1.   1.   0.5  4. ]
 [ 0.   1.   0.   4. ]
 [ 0.   0.   1.  -1. ]] Next Row Operation: -(1/2)*R2 + R0--> R0

Result of Row Operation
[[ 1.   1.   0.   4.5]
 [ 0.   1.   0.   4. ]
 [ 0.   0.   1.  -1. ]]



### Part 3 Step b.) 

Repeat for the sub-matrix containing all entries above and to the left of the leading entry you just worked off of


In [330]:
print(A_b,"Next Row Operation: -1*R1 + R0--> R0")
print()

# Row Operation: -1*R1 + R0--> R0
print("Result of Row Operation")
A_b[0,:] = -1*A_b[1,:]+ A_b[0,:]
print(A_b, "All off diagonal entries of the coefficient matrix are 0 yay!")
print()

[[ 1.   1.   0.   4.5]
 [ 0.   1.   0.   4. ]
 [ 0.   0.   1.  -1. ]] Next Row Operation: -1*R1 + R0--> R0

Result of Row Operation
[[ 1.   0.   0.   0.5]
 [ 0.   1.   0.   4. ]
 [ 0.   0.   1.  -1. ]] All off diagonal entries of the coefficient matrix are 0 yay!



### Part 3 Step c.) 

Rewrite our system of equations from the manipulated augmented matrix above:

$x_1 + 0x_2 + 0x_3 = 0.5$

$0x_1 + 1x_2 + 0x_3 = 4$

$0x_1 + 0x_2 + 1x_3 = -1$

or

$x_1 = 0.5$

$x_2 = 4$

$x_3 = -1$

### We have solved our system of equations and found the unique solution!


$x = \begin{bmatrix}
\frac{1}{2} \\
4\\
-1\\
\end{bmatrix}$.

