# ENGR 225: Python for Linear Algebra

ENGR 225 is a two-part course consisting of:
*   Part 1: Introduction to Programming with Python
*   Part 2: Matrix Algebra for Engineers

We have now finished with Part 1 and are moving into Part 2, but we are *not* done with Python!

We will use Python to better understand Matrix Alegbra. We can also use it to check our work!

# 20.2 Matrices and Linear Systems

This section is intended to provide Python Tools that will complement Zybook Section **19.2 Matrices and Linear Systems**

## Creating a Matrix in Python

We will typically use the "array" routine from the numpy package to create matrices in Python. *Each matrix* will be enclosed in brackets, and then *each row* of the matrix will be enclosed in additional brackets, separated by commas. Each element within the rows are also separated by commas. For example the matrix:

$\begin{bmatrix}
3 & 1 & 8\\
0 & -4 & 5
\end{bmatrix}$

can be generated using the following code.

NOTE: * I use the decimal places after each number to store them as floats *

In [ ]:
import numpy as np
A = np.array([[3., 1., 8.],
              [0., -4., 5.]])
print(A)

[[ 3  1  8]
 [ 0 -4  5]]


If you don't want to type all the decimal places to make floats, you can also use the `dtype` argument:

In [ ]:
import numpy as np
A = np.array([[3, 1, 8],
              [0, -4, 5]], dtype=float)
print(A)

[[ 3.  1.  8.]
 [ 0. -4.  5.]]


## Checking the size of a Matrix in Python


To check the size of an `np.array`, use the `np.shape` routine. The output tells you the (# of rows, # of columns)

In [ ]:
import numpy as np
A = np.array([[3., 1., 8.],
              [0., -4., 5.]])
print(np.shape(A))

(2, 3)


## Creating a Row Matrix
(also known as a Row Vector)

Creating a row vector is just like creating a matrix like we did above. It is just a special case where we only have one row.


In [ ]:
import numpy as np
v = np.array([[3., 2., 5.]])
print(v)

[[3 2 5]]


## Creating a Column Matrix
(also known as a Column Vector)

Creating a column vector is just like creating a matrix like we did above. It is just a special case where we only have one column, so there is only one element in each row.

In [ ]:
import numpy as np
v = np.array([[3.], [2.], [5.]])
print(v)

[[3]
 [2]
 [5]]


## Creating a Zero Matrix

A zero matrix has all zero entries. We can create a zero matrix using the `np.zeros` routine, where the argument is a tuple that consists of the number of rows and the number of columns. You can create a zero matrix of whatever size you like by changing the number of rows and columns.

In [ ]:
import numpy as np
Z = np.zeros((2,3))
print(Z)

[[0. 0. 0.]
 [0. 0. 0.]]


## Creating a Diagonal Matrix


For a square matrix, the number of rows equals the number of columns.

A diagonal matrix is a square matrix that is zero everywhere except on the main diagonal. We can create a list of elements and then use the `np.diag` routine to put those elements on the main diagonal of a square matrix. The longer your list of elements, the larger your diagonal matrix.

In [ ]:
import numpy as np
element_list = [3., 2., 5.]
D = np.diag(element_list)
print(D)

[[3. 0. 0.]
 [0. 2. 0.]
 [0. 0. 5.]]


## Creating an Identity Matrix



An identity matrix is a square matrix where all the elements on the main diagonal are one, and all other elements are zero. We use the `np.identity` routine, where the argument is the # of rows of the square matrix. (Remember for a square matrix # of rows = # of columns.) You can make your identiy matrix any size you want by changing this argument.

In [ ]:
import numpy as np
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Finding the Transpose of a Matrix

The transpose of a matrix $A$, written $A^T$, is the matrix that has as rows the columns of $A$. Thus, if $A$ is an $m \ x \ n$ matrix, $A^T$ is an $n \ x \ m$ matrix.



In [ ]:
import numpy as np
A = np.array([[1., 2.],
              [3., 4.],
              [5., 6.]])
print("A=")
print(A)
A_transpose = np.transpose(A)
print("np.transpose(A)=")
print(A_transpose)

#Note another method: np.transpose(A) = A.T
print("A.T=")
print(A.T)

A=
[[1. 2.]
 [3. 4.]
 [5. 6.]]
np.transpose(A)=
[[1. 3. 5.]
 [2. 4. 6.]]
A.T=
[[1. 3. 5.]
 [2. 4. 6.]]


## Finding the Trace of a Square Matrix

The trace of a square matrix is the sum of the entries along the main diagonal.

In [ ]:
import numpy as np
A = np.array([[1., 2., 7.],
              [3., 4., 2.],
              [5., 6., 1.]])
print("A=")
print(A)
A_trace = np.trace(A)
print("np.trace(A)=")
print(A_trace)

#Note another method: np.trace(A) = A.trace()
print("A.trace()=")
print(A.trace())

A=
[[1 2 7]
 [3 4 2]
 [5 6 1]]
np.trace(A)=
6
A.trace()=
6


## Creating an Augmented Matrix

We can represent a system of equations using an "augmented matrix". The terms with variables are all moved to the left hand side of our equations,and any remaining constant is moved to the right hand side of each equation. The coefficients of the variables are represented as a matrix $A$, and the constants on the right hand side are represented as a column vector $b$. For example:

$ 3x_1 + x_2 + 8x_3 = 3$

$ \ \ \ \ \  -4x_2 + 5x_3 = 2$

Coefficient Matrix
$A = \begin{bmatrix}
3 & 1 & 8\\
0 & -4 & 5
\end{bmatrix}$

Constant Vector
$b = \begin{bmatrix}
3 \\
2
\end{bmatrix}$

Augmented Matrix
$= \begin{bmatrix}
3 & 1 & 8 & | & 3\\
0 & -4 & 5 &| & 2
\end{bmatrix}$

To do this in Python we use the `np.concatenate` routine.

In [ ]:
import numpy as np
A = np.array([[3.,1.,8.],
              [0.,-4.,5.]])
b = np.array([[3.], [2.]])
A_b = np.concatenate((A, b), axis = 1)
print('Augmented matrix:\n', A_b)

Augmented matrix:
 [[ 3  1  8  3]
 [ 0 -4  5  2]]


# 20.3 Elementary Row Operations

## Formatting Output for Row Operations

Before we start this section, you might want to change the default way that Python shows output. I like using this way:

In [ ]:
import numpy as np
np.set_printoptions(precision=4,suppress=True)

Where the `precision=4` specifies that it will show output for 4 decimal places, and the `suppress=True` specifies that very small numbers like $$4.328\ \text{x} \ 10^{-123}$$ are shown as zero. This helps with dealing with round-off errors.

## Row numbers

Unlike most textbooks, let's call the first row of the matrix "Row 0" to match the way that python does indexing.

In [ ]:
import numpy as np
A = np.array([[3.,1.,8.,6.],    #R0
              [0.,-4.,5.,11.],  #R1
              [7.,9.,3.,278.]]) #R2

R0 = A[0,:]
print('R0 =',R0)

R0 = [3. 1. 8. 6.]


## Row Operations

There are 3 types of allowable row operations:

* Switch Rows
* Multiple a row by a non-zero number
* Replace a row by itself plus multiple of another row

### Switch Rows

Suppose we want to perform the following row opperation: $$ {R}_1 \leftrightarrow \text{R}_2 $$

In [ ]:
import numpy as np
A = np.array([[3.,12.,9.,6.],   #R0
              [0.,-4.,5.,11.],  #R1
              [7.,9.,3.,278.]]) #R2
R1 = np.copy(A[1,:])
R2 = np.copy(A[2,:])
A[2,:] = R1
A[1,:] = R2
print(A)

[[  3.  12.   9.   6.]
 [  7.   9.   3. 278.]
 [  0.  -4.   5.  11.]]


### Multiply a row by a non-zero number

Suppose we want to perform the following row opperation: $$ \frac{1}{3}\text{R}_0 \rightarrow \text{R}_0 $$

In [ ]:
import numpy as np
A = np.array([[3.,12.,9.,6.],   #R0
              [0.,-4.,5.,11.],  #R1
              [0.,0.,2.,278.]]) #R2
A[0,:] = (1/3)*A[0,:]
print(A)

[[  1.   4.   3.   2.]
 [  0.  -4.   5.  11.]
 [  0.   0.   2. 278.]]


### Replace a row by itself plus multiple of another row

Suppose we want to perform the following row opperation: $$ \text{R}_1 + -2 \text{R}_0 \rightarrow \text{R}_1 $$

In [ ]:
import numpy as np
A = np.array([[1.,12.,9.,6.],   #R0
              [2.,-4.,5.,11.],  #R1
              [0.,9.,3.,278.]]) #R2
A[1,:] = A[1,:] + -2*A[0,:]
print(A)

[[  1.  12.   9.   6.]
 [  0. -28. -13.  -1.]
 [  0.   9.   3. 278.]]


## Ruduced Row Echelon Form

You can use Python to get a matrix into reduced row echelon form, using the Matrix routine from the sympy package. This will return the
* matrix in reduced row echelon form,
* followed by index of the pivot columns.

In [ ]:
import numpy as np
from sympy import Matrix
A_array = np.array([[1, 0, 1],  #Note this is already in RREF
                    [0, 1, 1]]) #Pivot Columns have index 0 and 1.
A =  Matrix(A_array)

print('Reduced row echelon form of A=')
print(A.rref(),'\n')

B = Matrix([[1, 2, 3, -1],
            [2, -1, -4, 8],
            [-1, 1, 3, -5],
            [-1, 2, 5, -6],
            [-1, -2, -3, 1]])

print('Reduced row echelon form of B =')
print(B.rref())

Reduced row echelon form of A=
(Matrix([
[1, 0, 1],
[0, 1, 1]]), (0, 1)) 

Reduced row echelon form of B =
(Matrix([
[1, 0, -1, 0],
[0, 1,  2, 0],
[0, 0,  0, 1],
[0, 0,  0, 0],
[0, 0,  0, 0]]), (0, 1, 3))


## Rank of a matrix

In [ ]:
import numpy as np
from numpy.linalg import matrix_rank
A = np.array([[1,1,0],
              [0,1,0],
              [1,0,1]])
print('Rank:\n', matrix_rank(A))

#convince ourself that rank matches number of basic variables in RREF
from sympy import Matrix
M =  Matrix(A)
print(M.rref(),'\n')

Rank:
 3
(Matrix([
[1, 0, 0],
[0, 1, 0],
[0, 0, 1]]), (0, 1, 2)) 



# 21.1 Matrix addition and scalar multiplication

## Matrix Addition
Matrix addition is simple using the numpy package:

In [ ]:
import numpy as np
A = np.array([[0,2], [1,4]])
B = np.array([[3,1], [-3,2]])
print('A+B = :\n', A + B)
#Or
print('A+B = :\n', np.add(A, B))

A+B = :
 [[ 3  3]
 [-2  6]]
A+B = :
 [[ 3  3]
 [-2  6]]


Note, two matrices must have the same dimensions (number of rows and number of columns), in order to be added or subtracted. If they do not have the same dimensions they are "not conformable" for addition/subtraction.

In [ ]:
import numpy as np
A = np.array([[0,2], [1,4]])
print('Dimensions of A:',np.shape(A))
C = np.array([[3,1], [-3,2], [5,7]])
print('Dimensions of C:',np.shape(C))

print('Conformable for Addition?',np.shape(A)==np.shape(C))
# If A and C do not have the same dimensions,
# attempting to add them together will give an error...
print('A+C = :\n', A + C)

Dimensions of A: (2, 2)
Dimensions of C: (3, 2)
Conformable for Addition? False


ValueError: ignored

## Scalar Multiplication

Multiplying a matrix by a scalar is similarly simple using numpy:

In [ ]:
import numpy as np
c = 2
A = np.array([[0,2], [1,4]])
print('cA = :\n', c*A)

cA = :
 [[0 4]
 [2 8]]


# 21.2 Matrix Multiplication

The symbols for matrix multiplication using numpy are slightly less intiutive than addition, but still fairly simple. The @ symbol is used. Remember that the order of matrix multiplication matters!

In [ ]:
import numpy as np
A = np.array([[0,2], [1,4]])
B = np.array([[1,3], [2,1]])
print('AB = :\n', A @ B)

# Note AB is NOT equal to BA!
print('BA = :\n', B @ A)

AB = :
 [[4 2]
 [9 7]]
BA = :
 [[ 3 14]
 [ 1  8]]


If the number of columns in A is equal to the number of rows in B, then the matrices are "conformable for the multiplication" such that the product AB can be calculated.

In [ ]:
import numpy as np
A = np.array([[0,2], [1,4]])
print('Dimensions of A:',np.shape(A))
C = np.array([[3,1,4], [-3,2,9]])
print('Dimensions of C:',np.shape(C))

print('Conformable for Multiplication?',np.shape(A)[1]==np.shape(C)[0])
# If A and C do not have the same dimensions,
# attempting to add them together will give an error...
print('AC = :\n', A@C)

Dimensions of A: (2, 2)
Dimensions of C: (2, 3)
Conformable for Multiplication? True
AC = :
 [[-6  4 18]
 [-9  9 40]]


# 21.4 Inverse of a Matrix

We can use the inv function from the np.linalg package to calculate the inverse of a matrix. A matrix multiplied by its inverse produces the identity matrix. (The inverse of a matrix exists if the determinant is non-zero. We will cover determinants later in the course.)

In [ ]:
import numpy as np
A = np.array([[1, 2, 1],
              [4, 4, 5],
              [6, 7, 7]])
A_i = np.linalg.inv(A)
print(f'A inverse:\n{A_i}')
I = np.round(A @ A_i)
print(f'A times A_i resulsts in I_3:\n{I}')
I = np.round(A_i @ A)
print(f'A_i times A resulsts in I_3:\n{I}')


A inverse:
[[-7. -7.  6.]
 [ 2.  1. -1.]
 [ 4.  5. -4.]]
A times A_i resulsts in I_3:
[[ 1. -0.  0.]
 [-0.  1.  0.]
 [ 0. -0.  1.]]
A_i times A resulsts in I_3:
[[ 1.  0.  0.]
 [ 0.  1. -0.]
 [ 0. -0.  1.]]


# 21.5 Solving a system using an inverse matrix

A system of equations can be written using matrix notation as, Ax=b. If A is invertible as A_i, then x = A_i multiplied by the vector b.

In [ ]:
import numpy as np
A = np.array([[1, 2, 1],
              [4, 4, 5],
              [6, 7, 7]])
b = [[4],[2],[1]]
x = np.linalg.inv(A)@b
print(x)

[[-36.]
 [  9.]
 [ 22.]]


# 21.8 LU Decomposition



In [ ]:
import numpy as np
from scipy.linalg import lu
A = np.array([[2, 1, 1, 0],
              [4, 3, 3, 1],
              [8, 7, 9, 5],
              [6, 7, 9, 8]])
P, L, U = lu(A)
print(f'Permutation matrix:\n{P}')
print(f'Lower triangular matrix:\n{np.round(L, 2)}')
print(f'Upper triangular matrix:\n{np.round(U, 2)}')
A_recover = np.round(P @ L @ U, 1)
print(f'PLU multiplicatin:\n{A_recover.astype(float)}')

Pivot matrix:
[[0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]]
Lower triangular matrix:
[[ 1.    0.    0.    0.  ]
 [ 0.75  1.    0.    0.  ]
 [ 0.5  -0.29  1.    0.  ]
 [ 0.25 -0.43  0.33  1.  ]]
Upper triangular matrix:
[[ 8.    7.    9.    5.  ]
 [ 0.    1.75  2.25  4.25]
 [ 0.    0.   -0.86 -0.29]
 [ 0.    0.    0.    0.67]]
PLU multiplicatin:
[[2 1 1 0]
 [4 3 3 1]
 [8 7 9 5]
 [6 7 9 8]]


# 21.9 Norms and Distances

In [ ]:
import numpy as np
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
np.linalg.norm(A, 'fro')
#help(np.linalg.norm)

Help on function norm in module numpy.linalg:

norm(x, ord=None, axis=None, keepdims=False)
    Matrix or vector norm.
    
    This function is able to return one of eight different matrix norms,
    or one of an infinite number of vector norms (described below), depending
    on the value of the ``ord`` parameter.
    
    Parameters
    ----------
    x : array_like
        Input array.  If `axis` is None, `x` must be 1-D or 2-D, unless `ord`
        is None. If both `axis` and `ord` are None, the 2-norm of
        ``x.ravel`` will be returned.
    ord : {non-zero int, inf, -inf, 'fro', 'nuc'}, optional
        Order of the norm (see table under ``Notes``). inf means numpy's
        `inf` object. The default is None.
    axis : {None, int, 2-tuple of ints}, optional.
        If `axis` is an integer, it specifies the axis of `x` along which to
        compute the vector norms.  If `axis` is a 2-tuple, it specifies the
        axes that hold 2-D matrices, and the matrix norms of these

Condition Number

In [ ]:
import numpy as np
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
np.linalg.norm(A, 'fro')
condA = np.linalg.cond(A)
print("condition number of A=",condA)

condition number of A= 3.813147060626918e+16


# 22.3 Dot Product

In [ ]:
import numpy as np
a = [1,2,3]
b = [4,5,6]
a_dot_b = np.dot(a,b)
print(a_dot_b)

32


# 22.4 Cross Product

In [ ]:
import numpy as np
a = [1,2,3]
b = [4,5,6]
a_cross_b = np.cross(a,b)
print(a_cross_b)

[-3  6 -3]
[0 0 0]


# 24.1 Determinant

In [ ]:
from numpy.linalg import det
M = np.array([[0,2,1,3],
            [3,2,8,1],
             [1,0,0,3],
             [0,3,2,1]])
print('M:\n', M)
print('Determinant: %.1f'%det(M))


M:
 [[0 2 1 3]
 [3 2 8 1]
 [1 0 0 3]
 [0 3 2 1]]
Determinant: -38.0


# 27.1 Eigenvalues and Eigenvectors

In [ ]:
import numpy as np
A = np.array([[-6, 3],
              [4, 5]])
values, vectors = np.linalg.eig(A)
print(f'Eigenvalues of A:\n{values}\n')
print(f'Eigenvectors of A:\n{vectors}')

Eigenvalues of A:
[-7.  6.]

Eigenvectors of A:
[[-0.9486833  -0.24253563]
 [ 0.31622777 -0.9701425 ]]
