# Solving Systems of Equations Review





In [ ]:
import numpy as np
np.set_printoptions(precision=4,suppress=True)

We have covered the following methods to solve systems of equations:

* Gaussian Elimination
* Gauss-Jordan Elimination
* The Inverse

For example, suppose you have the following system of equations:

$2x_1 + 2x_2 + x_3 = 8$

$4x_1 + 2x_2 + 6x_3 = 4$

$x_2 + 2x_3 = 2$

We can rewrite this system of equations as:

$Ax = b$

where $A$ is the coefficient matrix, $x$ is a column vector of the solutions, and $b$ is a column vector of the constants on the right hand side.

The associated coefficient matrix A is:

In [ ]:
A = np.array([[2,2,1],
             [4,2,6],
              [0,1,2]],dtype=float)
print(A)

[[2. 2. 1.]
 [4. 2. 6.]
 [0. 1. 2.]]


The associated column vector of constants (for the right hand side of the system of equations) is:

In [ ]:
b = np.array([[8],
              [4],
              [2]],dtype=float)

We can try any of the methods above to solve this system! Let's test them all...

## Gaussian Elimination

For Gaussian Elimination, we first need to create an augmented matrix [A|b]:

In [ ]:
A_b = np.concatenate((A, b), axis = 1)
print('Augmented matrix:\n', A_b)

Next we perform *forward elimination* using row operations until the augmented matrix is in Echelon Form:

In [ ]:
#R1 - 2*R0 --> R1
A_b[1,:] = A_b[1,:] - 2*A_b[0,:]
print(A_b)

In [ ]:
#R2 + (1/2)*R1 --> R2
A_b[2,:] = A_b[2,:] + (1/2)*A_b[1,:]
print(A_b)

Now that our system is in Echelon Form, we rewrite our system of equations as

$2x_1 + 2x_2 + x_3 = 8$

$-2x_2 + 4x_3 = -12$

$4x_3 = -4$


The next part of Gaussian Elimination is *back substitution*:

Starting with the bottom equation we find:

$x_3 = -1$.

We can plug that into the equation above it:

$-2x_2 + 4(-1) = -12$

And now we can solve for $x_2$:

$x_2 = 4$.

Now we can plug $x_3$ and $x_2$ into the top equation,

$2x_1 + 2*(4) + (-1) = 8$

and we can find $x_1$:

$x_1 = \frac{1}{2}$.

We have solved our system of equations!


$x = \begin{bmatrix}
\frac{1}{2} \\
4\\
-1\\
\end{bmatrix}$.



We can check this using code to make sure that $A$ matrix multiplied by our solutions for $x$ really does equal $b$:

In [ ]:
x = np.array([[0.5],
              [4],
              [-1]])
print(A@x)
print(b)

Or like this by using the computer to do the algebra for us:

In [ ]:
x3 = A_b[2,3]/A_b[2,2]
x2 = (A_b[1,3]-A_b[1,2]*x3)/A_b[1,1]
x1 = (A_b[0,3]-A_b[0,1]*x2-A_b[0,2]*x3)/A_b[0,0]
print(x1,x2,x3)

## Gauss-Jordan Elimination

Gauss-Jordan Elimination starts out doing forward elimination just like Gaussian Elimination, but uses more row operations to get to *REDUCED* ECHELON FORM.

Just like Guassian Elimination we start with the Augmented Matrix [A|b]

In [ ]:
A_b = np.concatenate((A, b), axis = 1)
print('Augmented matrix:\n', A_b)

We use the same row operations to get to echelon form:

In [ ]:
#R1 - 2*R0 --> R1
A_b[1,:] = A_b[1,:] - 2*A_b[0,:]
print(A_b)

In [ ]:
#R2 + (1/2)*R1 --> R2
A_b[2,:] = A_b[2,:] + (1/2)*A_b[1,:]
print(A_b)

This is where we left off with Gaussian Elimination, but we continue on with more row operations.

Next we use row operations to make the diagonal entries 1.

In [ ]:
#(1/2)*R0-->R0
A_b[0,:] = (1/2)*A_b[0,:]
print(A_b)

In [ ]:
#(-1/2)*R1-->R1
A_b[1,:] = (-1/2)*A_b[1,:]
print(A_b)

In [ ]:
#(1/4)*R2-->R2
A_b[2,:] = (1/4)*A_b[2,:]
print(A_b)

Lastly we make all the entries above the pivots zero, starting with the bottom-right and moving upwards and then left.

In [ ]:
#R1 + 2*R2 --> R1
A_b[1,:] = A_b[1,:] + 2*A_b[2,:]
print(A_b)

In [ ]:
#R0 - (1/2)*R2 --> R0
A_b[0,:] = A_b[0,:] + (-1/2)*A_b[2,:]
print(A_b)

In [ ]:
#R0 - R1 --> R0
A_b[0,:] = A_b[0,:] - A_b[1,:]
print(A_b)

Rewriting our system of equations we have:

$x_1 = 1/2$

$x_2 = 4$

$x_3 = -1$

Thankfully this is the same solution that we found with Gaussian Elimination and LU Decomposition!

$x = \begin{bmatrix}
\frac{1}{2} \\
4\\
-1\\
\end{bmatrix}$.

We can also check this using the Matrix routine from the sympy package:

In [ ]:
from sympy import Matrix
A_b_matrix =  Matrix(A_b)

print(f'Reduced row echelon form of [A|b]=')
print(A_b_matrix.rref(),'\n')

This shows us the augmented matrix in reduced row echelon form, followed by the index of each pivot column (In this case: (0,1,2)).

This matches. Great!

## The Inverse

We find the inverse of a matrix by starting with a different augmented matrix, $[A|I]$, where $I$ is the identity matrix that is the same size as A. (A must be a square matrix for this to work.)

In [ ]:
print("A=")
print(A)
n,m = np.shape(A)
print("I=")
I = np.identity(n)
print(I)
A_I = np.concatenate((A, I), axis = 1)
print('Augmented matrix [A|I]:\n', A_I)

Next we perform row operations on the augmented matrix until the left side of the matrix turns into the identity matrix. (This is only possible if the matrix is "invertible").

These will be the same row operations that we used for Guass-Jordan Elimination.

In [ ]:
#R1 - 2*R0 --> R1
A_I[1,:] = A_I[1,:] - 2*A_I[0,:]
print(A_I)

In [ ]:
#R2 + (1/2)*R1 --> R2
A_I[2,:] = A_I[2,:] + (1/2)*A_I[1,:]
print(A_I)

In [ ]:
#(1/2)*R0-->R0
A_I[0,:] = (1/2)*A_I[0,:]
print(A_I)

In [ ]:
#(-1/2)*R1-->R1
A_I[1,:] = (-1/2)*A_I[1,:]
print(A_I)

In [ ]:
#(1/4)*R2-->R2
A_I[2,:] = (1/4)*A_I[2,:]
print(A_I)

In [ ]:
#R1 + 2*R2 --> R1
A_I[1,:] = A_I[1,:] + 2*A_I[2,:]
print(A_I)

In [ ]:
#R0 - (1/2)*R2 --> R0
A_I[0,:] = A_I[0,:] + (-1/2)*A_I[2,:]
print(A_I)

In [ ]:
#R0 - R1 --> R0
A_I[0,:] = A_I[0,:] - A_I[1,:]
print(A_I)

Now the right hand side of our matrix is the inverse of A!

$A^{-1} = \begin{bmatrix}
\frac{1}{8} & \frac{3}{16} & -\frac{5}{8} \\
\frac{1}{2} & -\frac{1}{4} &\frac{1}{2}\\
-\frac{1}{4} & \frac{1}{8} & \frac{1}{4}\\
\end{bmatrix}$

In [ ]:
Ainv = A_I[:,3:]
print(Ainv)

By definition, the following should be true for the inverse:

$A A^{-1} = I$.

$A^{-1} A  = I$.

Let's check this to make sure we calculated the inverse correctly.

In [ ]:
print(A@Ainv)
print(Ainv@A)

Looks good!

Now let's use this inverse to solve our system of equations.

Remember that we started out with
$Ax = b$

If we matrix multiply on the left by the inverse for both sides:

$A^{-1}Ax = A^{-1}b$

which becomes:

$x = A^{-1} b$.

So this tells us that if we want to find $x$, we simply have to multiply the inverse we found with $b$:



In [ ]:
x = Ainv@b
print(x)

It worked!

This solution matches the solution we found using all the other methods above.

We can also check this using the inv function from the np.linalg package:

In [ ]:
x = np.linalg.inv(A)@b
print(x)

Looks good!