# Lab Week 11

You will turn in TWO documents via Canvas upload:
1. Handwritten answers
2. Python Jupyter Notebook answer

You are encouraged to use:
* [Python for Linear Algebra Reference Sheet](https://humboldt.cloudbank.2i2c.cloud/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fbludka%2Fengr225-materials-fa2024&branch=main&urlpath=lab%2Ftree%2Fengr225-materials-fa2024%2F00_resources%2FPython_Toolbox_for_Linear_Algebra.ipynb)

<font color='red'>***Answer all questions by hand first, then repeat the task using Python in this notebook.***<font> <font color='magenta'> If a question does not require a calculation, `print()` your answer and thought process to the screen, in addition to writing it in your handwritten version.

Run the following code to import numpy and chose a more convenient output format

In [2]:
import numpy as np
np.set_printoptions(precision=4,suppress=True)

## 1. Trace of a Matrix

What is the trace of the following matrices? *When you do the coding part, use the `np.trace()` function. See the [Python for Linear Algerba Reference Sheet](https://humboldt.cloudbank.2i2c.cloud/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fbludka%2Fengr225-materials-fa2024&branch=main&urlpath=lab%2Ftree%2Fengr225-materials-fa2024%2F00_resources%2FPython_Toolbox_for_Linear_Algebra.ipynb) for examples.*

### Question 1.1

In [2]:
A = np.array([[1., 1., 5.],  #R0
              [0., 2., 2.],  #R1
              [1., 0., 0.]]) #R2

#complete task here (after calculating by hand)
print("The trace of A is ?", np.trace(A)) #I gave you this one

The trace of A is ? 3.0


### Question 1.2



In [3]:
A = np.array([[7.,     1.45,  5.1],  #R0
              [3.566,  22.,   2.4],  #R1
              [1.222,  300.5, 1.22]]) #R2

#complete task here (after calculating by hand)
print("The trace of A is ?") #modify

The trace of A is ?


## 2. Tranpose of a Matrix

What is the transpose of the following matrices? *When you do the coding part, use the `np.transpose()` method or `A.T`. Examples in the [Reference Sheet](https://humboldt.cloudbank.2i2c.cloud/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fbludka%2Fengr225-materials-fa2024&branch=main&urlpath=lab%2Ftree%2Fengr225-materials-fa2024%2F00_resources%2FPython_Toolbox_for_Linear_Algebra.ipynb)*

### Question 2.1

In [4]:
A = np.array([[3., 1., 0.,-1.],  #R0
              [-4.,0., 1., 2.],  #R1
              [3., 4., 1.,-3.]]) #R2

#complete task here (after calculating by hand)
print("The transpose of A is ? \n")#modify

The transpose of A is ? 



### Question 2.2

For this question find ($A^\text{T}$)$^\text{T}$. Calculate $A^\text{T}$ first. Then take the transpose again. Show all steps.

In [5]:
A = np.array([[0., 2., 5.],  #R0
              [1.,-6., 13.], #R1
              [2., 0., 0.]]) #R2

#complete task here (after calculating by hand)
print("The transpose of the transpose of A is ? \n") #modify

The transpose of the transpose of A is ? 



## 3. Matrix Addition

If mathematically possible, add the following matrices together.

If the operation is not possible, write on your handwritten sheet "Not possible because {your reason here}". You may use the regular addition symbol `+` to perform this task as shown in the [Reference Sheet](https://humboldt.cloudbank.2i2c.cloud/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fbludka%2Fengr225-materials-fa2024&branch=main&urlpath=lab%2Ftree%2Fengr225-materials-fa2024%2F00_resources%2FPython_Toolbox_for_Linear_Algebra.ipynb)

Similarly, in your code output: `print("Not possible because {your reason here}")`.

Hint: use `np.shape()` to check the shape of each matrix



### Question 3.1

In [6]:
A = np.array([[0., 1.],  #R0
              [0., 2.],  #R1
              [1., 0.]]) #R2

B = np.array([[3., 0.],  #R0
              [4., 4.],  #R1
              [3., 0.]]) #R2

#complete task here (after calculating by hand)
print("A plus B = ?\n") #modify

A plus B = ?



### Question 3.2

In [7]:
A = np.array([[1., 1., 5.],  #R0
              [0., 2., 2.],  #R1
              [1., 0., 0.]]) #R2

B = np.array([[3., 0., 1.],  #R0
              [4., 4., 7.]]) #R1

#complete task here (after calculating by hand)
print("A plus B = ?\n")#modify

A plus B = ?



### Question 3.3

Python allows this, but it should not if it was truly following linear algebra rules. Why should this not be allowed according to our linear algebra rules?

In [8]:
A = np.array([[6.],  #R0
              [0.],  #R1
              [1.]]) #R2

B = np.array([[3., 0., 1.]]) #R0

#complete task here (after calculating by hand)
print("A plus B = ?\n")#modify

A plus B = ?



### Question 3.4

Using A and B from Question 3.3, What is A + $B^\text{T}$?

Note: $B^\text{T}$ is the transpose of B.

In [9]:
#complete task here (after calculating by hand)
print("A plus B_transpose = ?\n")#modify

A plus B_transpose = ?



## 4. Scalar Multiplication

Answer the following scalar multiplication problems. You may use the regular multiplication `*` symbol to perform this task as shown in the [Reference Sheet](https://humboldt.cloudbank.2i2c.cloud/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fbludka%2Fengr225-materials-fa2024&branch=main&urlpath=lab%2Ftree%2Fengr225-materials-fa2024%2F00_resources%2FPython_Toolbox_for_Linear_Algebra.ipynb)

### Question 4.1



In [3]:
c = 2 #scalar
A = np.array([[0., 1.],  #R0
              [0., 2.],  #R1
              [1., 0.]]) #R2

#complete task here (after calculating by hand)
print("cA = ?\n")#modify

cA = ?



### Question 4.2



In [11]:
c = 3
A = np.array([[3., 0., 1.]])

#complete task here (after calculating by hand)
print("cA = ?\n") #modify

cA = ?



### Question 4.3

In [ ]:
c = 200 #scalar
A = np.identity(4) #if you aren't sure what the np.identity function does, print out A to see!

#complete task here (after calculating by hand)
print("cA = ?\n") #modify

A= [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
cA = ?



### Question 4.4

In [ ]:
c = 9 #scalar
A = np.zeros((3,2))#if you aren't sure what the np.zeros function does, print out A to see!

#complete task here (after calculating by hand)
print("cA = ?\n") #modify

A= [[0. 0.]
 [0. 0.]
 [0. 0.]]
cA = ?



## 5. Matrix Multiplication

Matrices can only be multiplied if their inner dimensions are equal. Multiplying $A$ with dimensions $m$ x $n$, by $B$ with dimensions $n$ x $p$, results in a matrix $AB$ of size $m$ x $p$.

<img src="https://lh3.googleusercontent.com/pw/ADCreHcSe-OO0Eh4TlZyt0RYkgpbCN79xoF0AUhV7yAJZWp1a-miuOhNnOR_M2zjdX14guNXEhFzT144A-bOzLDoSc_OLo_50S5DNwSIJot7mDI1xsvrDkrfjAXSuXsHIiFgzc0JxZ_6mGEEC2M6TR_w3jcv=w584-h371-s-no?authuser=0" width="350">

Matrix multiplication follows the row-column rule.

<img src="https://lh3.googleusercontent.com/pw/ADCreHdYJ6RYsDC9eDW-1SuX4Q1MdewyfC4pCMF9r3vOKesFMTrTkqF-JklZSAxXk0p0MVioYObI405XxPpVSVkQayTJsi_Js9-NSrLm932t1gsNvWU680Jrs_4D5n_iJo3HoEu-aZGT8G_8O2BsQy_gDUsk=w1400-h848-s-no?authuser=0" width="350">



Show all steps (as in the figure above) by hand. Check your work using Python where `@` is the operator used for matrix multiplication. (*Examples in the [Reference Sheet](https://humboldt.cloudbank.2i2c.cloud/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fbludka%2Fengr225-materials-fa2024&branch=main&urlpath=lab%2Ftree%2Fengr225-materials-fa2024%2F00_resources%2FPython_Toolbox_for_Linear_Algebra.ipynb)*)

If the matrices are not conformable for multiplication, write on your handwritten sheet "Not possible because {your reason here}".

Similarly, in your code output: `print("Not possible because {your reason here}")`.

Hint: use `np.shape()` to check the shape of each matrix

### Question 5.1

In [14]:
A = np.array([[2., 3.],  #R0
              [1., 4.]]) #R1

B = np.array([[5., 1.],  #R0
              [2., 3.]]) #R1

#complete task here (after calculating by hand)
print("A matrix mult B = ?\n")#modify

A matrix mult B = ?



### Question 5.2


In [15]:
A = np.array([[1., 2.], #R0
              [3., 4.], #R1
              [5., 6.]])#R2

B = np.array([[2., 1., 3.],  #R0
              [4., 2., 1.]]) #R1

#complete task here (after calculating by hand)
print("A matrix mult B = ?\n")#modify

A matrix mult B = ?



### Question 5.3

In [16]:
A = np.array([[1., 0., -1, 2.,], #R0
              [2., 1., 1., -3]])#R1

B = np.array([[-1., -1., 0., 3], #R0
              [1., 0., 2., -1]]) #R1

#complete task here (after calculating by hand)
print("A matrix mult B = ?\n")#modify

A matrix mult B = ?



## 6. More Matrix Multiplication

Use the following matrices for your calculations in this section:

<img src="https://lh3.googleusercontent.com/pw/AP1GczM09KNAvcMl94MDU0lB5Zy5Sgtku7FV087rMLdIiwVo_pTQyQWw3c8DU4Rvh0DqVjbebcg_1AMJDt5pQ5F2C9TgpJUSYdWYr1-WnFnznNg8grvspqsj8Bi-hwG6jo2OPW3eKfNaht6nCQy5uasn_aZI=w1062-h184-s-no-gm?authuser=0" width="500">

Show all steps (as in the previous problems) by hand. Check your work using Python where `@` is the operator used for matrix multiplication. (*Examples in the [Reference Sheet](https://humboldt.cloudbank.2i2c.cloud/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fbludka%2Fengr225-materials-fa2024&branch=main&urlpath=lab%2Ftree%2Fengr225-materials-fa2024%2F00_resources%2FPython_Toolbox_for_Linear_Algebra.ipynb)*)

If the matrices are not conformable for multiplication, write on your handwritten sheet "Not possible because {your reason here}".

Similarly, in your code output: `print("Not possible because {your reason here}")`.

Hint: use `np.shape()` to check the shape of each matrix

### Question 6.1

$BC = ?$

In [17]:
# your code here (after calculating by hand)

### Question 6.2

$C^TB =?$

In [18]:
# your code here (after calculating by hand)

### Question 6.3

$3AB - 5D =?$

In [19]:
# your code here (after calculating by hand)

### Question 6.4

$D(C+B)=?$

In [20]:
# your code here (after calculating by hand)

## 7. Inverse of a 2x2 Matrix

Calculate the inverse of the following 2x2 Matrices using the following formula:

<img src="https://lh3.googleusercontent.com/pw/AP1GczOtLKgq_Yp-2awvNmyM3PdKoeCVpRlwrTwUM0A0XaaAgajeIbecQGwqS-xddDn2p8NR77hikFwRpUa7l9lTnfHtIsN25X7eQ2XtdbKyWTMl8_EHO_jAReBJ4F8qAKpOclub1lmer-dyjZ1OLrdLCUgB=w643-h217-s-no-gm?authuser=0" width="500">

If the determinant is zero, print to the screen `print("Singular Matrix. The inverse does not exist because the determinant is zero and division by zero is not allowed!")`.

Show all steps by hand. **Check your work in Python using TWO methods**:

* `np.linalg.inv()` (*Examples in the [Reference Sheet](https://humboldt.cloudbank.2i2c.cloud/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fbludka%2Fengr225-materials-fa2024&branch=main&urlpath=lab%2Ftree%2Fengr225-materials-fa2024%2F00_resources%2FPython_Toolbox_for_Linear_Algebra.ipynb)*)
* If the inverse exists, multiply the original matrix by it's inverse using the `@` symbol to make sure the Identity Matrix is returned.

### Question 7.1

Find $A^{-1}$

In [21]:
A = np.array([[2., 4.],
              [1., 2.]])
#your code here (after completing it by hand)
# check using both methods!

### Question 7.2

Find $B^{-1}$

In [22]:
B = np.array([[2., 3.],
              [1., 4.]])
#your code here (after completing it by hand)
# check using both methods!

### Question 7.3

Find $C^{-1}$

In [23]:
C = np.array([[3., 1.],
              [2., 5.]])
#your code here (after completing it by hand)
# check using both methods!

### Question 7.4

Write a user function called `mat_inv()` that calculates the inverse of a 2x2 matrix *using the formula provided above*. The function takes a numpy array as an argument and returns the inverse as another numpy array. Call your function to make sure it works. (You do not need to do this one by hand, but since you already have your drawing kit out, it could be a good opportunity to make a flow chart!)

If the user provides an argument that is NOT a 2x2 matrix, print `"The matrix must be 2x2."` and return nothing.

If the matrix does not have an inverse print `"Singular Matrix. The inverse does not exist because the determinant is zero and division by zero is not allowed!")` and return *nothing*.

In [24]:
# your code here

## 8. Gaussian Elimination

### Question 8.1

Solve this system of equations by hand using [Gassian Elimination](https://humboldt.cloudbank.2i2c.cloud/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fbludka%2Fengr225-materials-fa2024&branch=main&urlpath=lab%2Ftree%2Fengr225-materials-fa2024%2F00_resources%2FElimination_Methods_for_Systems_of_Equations_with_Unique_Solution.ipynb)

$x_1+2x_2−x_3=3$

$2x_1−x_2+x_3=1$

$x_1+x_2+x_3=6$
​

Check your row operations using Python. I recommend doing this check after completing each row operation as you go.


In [ ]:
# check your work here

You are done!

Two files are required for submission:

* One single PDF file of your hand written solutions
  * Use [AdobeScan](https://acrobat.adobe.com/us/en/mobile/scanner-app.html) on your phone in order to convert pictures into **one single** PDF file
* Notebook (.ipynb) file of your programmed solutions. 