# Lab Week 13
You will turn in TWO documents via Canvas upload:
1. Handwritten answers
2. Python Jupyter Notebook answer

You are encouraged to use:
* [Python for Linear Algebra Reference Sheet](https://colab.research.google.com/drive/1W14SPExQsbqShGx5g_oJgfxncKHssZgO?usp=sharing)
* [Elimination Notes](https://colab.research.google.com/drive/1338X5kaipXQHWe-ofPltdzpaB3sRX1M8?usp=sharing)
* [Echelon Forms and Characterizing Solutions to Systems of Equations](https://humboldt.cloudbank.2i2c.cloud/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fbludka%2Fengr225-materials-fa2024&branch=main&urlpath=lab%2Ftree%2Fengr225-materials-fa2024%2F00_resources%2FEchelon_Forms_and_Characterizing_Solutions_to_Systems_of_Equations.ipynb)
* Lecture Notes:
    * [Elimination Methods for Systems with Unique Solution](https://docs.google.com/presentation/d/1oi8hM7kyn5FGcA7vfJpGC1etQT1pagTmADT9fNLguLE/edit?usp=sharing)
    * [Elimination Methods for Inconsistent and Non-Unique Systems](https://docs.google.com/presentation/d/1ZFaO8ykgwQkmGKcvaMrJn3j2mHJDxbRLuc1I_ZS896U/edit?usp=sharing)

<font color='red'>***Answer all questions by hand first, then repeat the task using Python in this notebook.***<font> <font color='magenta'> If a question does not require a calculation, `print()` your answer and thought process to the screen, in addition to writing it in your handwritten version.

## 1. Gauss-Jordan Elimination [10 pts each]

Perform the following tasks for each system of equation below

> a.) Create a coefficient matrix, named $A$. [0.5pt]

> b.) Create a column vector (mx1 matrix) of the constants, named $b$. [0.5pt]

> c.) Concatenate $A$ and $b$ to create an augmented matrix $[A | b]$. (*When you do this in Python, make sure to use code to do this. [1pt]

> d.) Use **Gausss-JORDAN elimination** to solve your system of equations. [6 pts]

> e.) Write on paper/print to the screen the basic and free variables of the system. [0.5pt]

> f.) Write on paper/print to the screen the rank and nullity of coefficient matrix. Then also state the rank of the augmented matrix. [1pt]

> g.) Write on paper/print to the screen whether the solution to the system is **consistent** or **inconsistent**. [0.5pt]

> h.) Write on paper/print to the screen whether the solution to the system is **unique** or **non-unique**. If the system is inconsistent, write *N/A*. [0.5pt]

> i.) Write on paper/print to the screen the solution for each of your variables. *If the solution is non-unique, write your solutions in terms of your free variables. If the solution does not exist, write DNE.* [1pt]






In [ ]:
# run this code!
import numpy as np
np.set_printoptions(precision=4,suppress=True)

### Question 1.1

Make sure to complete steps a-g above for the following system:

> $x_1 + 4x_4 = 6 $

> $x_2 - 3x_4 = 2 $

> $x_3 + x_4 = -5 $

In [ ]:
# Your code here. I have included reminders of each step in comments.

#a) coefficient matrix A
# your code here

#b) vector of constants b
# your code here

#c) augmented matrix A|b
# your code here

#d) Gausss-JORDAN Elimination
# your code here

#e) basic and free variables? print to the screen
# your code here

#f) rank and nullity? print to the screen
# your code here

#g) consistent? print to the screen
# your code here

#h) unique? print to the screen
# your code here

#i) solution print to the screen
# your code here (after you calculate it by hand)

### Question 1.2

Make sure to complete steps a-g above for the following system:

> $2x_1 + 2x_2 + 2x_3 = 0 $

> $-2x_1 + 5x_2 + 2x_3 = 1 $

> $8x_1 + x_2 + 4x_3 = -1 $

In [ ]:
#a) coefficient matrix A
# your code here

#b) vector of constants b
# your code here

#c) augmented matrix A|b
# your code here

#d) Gausss-JORDAN Elimination
# your code here

#e) basic and free variables? print to the screen
# your code here

#f) rank and nullity? print to the screen
# your code here

#g) consistent? print to the screen
# your code here

#h) unique? print to the screen
# your code here

#i) solution print to the screen
# your code here (after you calculate it by hand)

### Question 1.3

Make sure to complete steps a-g above for the following system:

> $x_1 - x_3 + 2x_6=  4$

> $x_2 + 2x_3 -6x_5 -x_6 =  0$

> $4x_1 - 4x_3 + x_4 -3x_5 + 12x_6 = 18$

> $2x_1 -2x_3  + 4x_6 = 8$

In [ ]:
#a) coefficient matrix A
# your code here

#b) vector of constants b
# your code here

#c) augmented matrix A|b
# your code here

#d) Gausss-JORDAN Elimination
# your code here

#e) basic and free variables? print to the screen
# your code here

#f) rank and nullity? print to the screen
# your code here

#g) consistent? print to the screen
# your code here

#h) unique? print to the screen
# your code here

#i) solution print to the screen
# your code here (after you calculate it by hand)

### Question 1.4

Make sure to complete steps a-g above for the following system:

> $x_1 + 2x_2 + 5x_4 =  0$

> $x_3 +9x_4  =  4$

> $x_1 + 2x_2 + 5x_4 = -5$

In [ ]:
#a) coefficient matrix A
# your code here

#b) vector of constants b
# your code here

#c) augmented matrix A|b
# your code here

#d) Gausss-JORDAN Elimination
# your code here

#e) basic and free variables? print to the screen
# your code here

#f) rank and nullity? print to the screen
# your code here

#g) consistent? print to the screen
# your code here

#h) unique? print to the screen
# your code here

#i) solution print to the screen
# your code here (after you calculate it by hand)

## 2. Inverse of a Matrix [10 pts each]

Let $A$ be a square matrix (size $n$x$n$). The inverse of $A$ is denoted by $A^{-1}$.

We can find the inverse $A^{-1}$ by following these steps:

1. Form an augmented matrix of $[A|I]$, where $I$ is the identity matrix with the same size as A.

2. Use row operations to reduce the left-hand portion into reduced row-echelon form.

3. If the augmented matrix after step 2 has the form $[I|B]$, then $B = A^{-1}$. If it does not have this form, then $A$ does not have an inverse.

If this is the system of equations:
> $-2x_1 + 3x_2 + 5x_3 = 8 $

> $- 1x_2 = 1 $

> $1x_1 - 2x_2 + -2x_3 = 10 $

Then the coefficient matrix A is:

In [ ]:
A = np.array([[-2., 3., 5.],  #R0
              [0.,-1., 0.],   #R1
              [1., -2., -2.]]) #R2
print(A)

[[-2.  3.  5.]
 [ 0. -1.  0.]
 [ 1. -2. -2.]]


The identity matrix that is the same size as A is:

In [ ]:
I = np.identity(3)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


To find the inverse, first create the augmented matrix $[A|I]$:

In [ ]:
A_I = np.concatenate((A, I), axis = 1)
print(A_I)

[[-2.  3.  5.  1.  0.  0.]
 [ 0. -1.  0.  0.  1.  0.]
 [ 1. -2. -2.  0.  0.  1.]]


Then perform row operations to try to get the *left* size of the augmented matrix to turn into the identiy:

In [ ]:
#R2 + (-1/2)R0 -->R2
A_I[2,:] = A_I[2,:] + (1/2)*A_I[0,:]
print(A_I)

[[-2.   3.   5.   1.   0.   0. ]
 [ 0.  -1.   0.   0.   1.   0. ]
 [ 0.  -0.5  0.5  0.5  0.   1. ]]


In [ ]:
#R2 + (-1/2)R1 -->R2
A_I[2,:] = A_I[2,:] + (-1/2)*A_I[1,:]
print(A_I)

[[-2.   3.   5.   1.   0.   0. ]
 [ 0.  -1.   0.   0.   1.   0. ]
 [ 0.   0.   0.5  0.5 -0.5  1. ]]


In [ ]:
#(-1/2)R0 --> R0
A_I[0,:] = (-1/2)*A_I[0,:]
print(A_I)

[[ 1.  -1.5 -2.5 -0.5 -0.  -0. ]
 [ 0.  -1.   0.   0.   1.   0. ]
 [ 0.   0.   0.5  0.5 -0.5  1. ]]


In [ ]:
#(-1)R1 --> R1
A_I[1,:] = (-1)*A_I[1,:]
print(A_I)

[[ 1.  -1.5 -2.5 -0.5 -0.  -0. ]
 [-0.   1.  -0.  -0.  -1.  -0. ]
 [ 0.   0.   0.5  0.5 -0.5  1. ]]


In [ ]:
#2*R2 --> R2
A_I[2,:] = 2*A_I[2,:]
print(A_I)

[[ 1.  -1.5 -2.5 -0.5 -0.  -0. ]
 [-0.   1.  -0.  -0.  -1.  -0. ]
 [ 0.   0.   1.   1.  -1.   2. ]]


In [ ]:
#R0 + 2.5*R2 -->R0
A_I[0,:] = A_I[0,:] + (2.5)*A_I[2,:]
print(A_I)

[[ 1.  -1.5  0.   2.  -2.5  5. ]
 [-0.   1.  -0.  -0.  -1.  -0. ]
 [ 0.   0.   1.   1.  -1.   2. ]]


In [ ]:
#R0 + 1.5*R1 -->R0
A_I[0,:] = A_I[0,:] + (1.5)*A_I[1,:]
print(A_I)

[[ 1.  0.  0.  2. -4.  5.]
 [-0.  1. -0. -0. -1. -0.]
 [ 0.  0.  1.  1. -1.  2.]]


In [ ]:
# Left side of A_I is the identity matrix
print(A_I[:,0:3])

[[ 1.  0.  0.]
 [-0.  1. -0.]
 [ 0.  0.  1.]]


In [ ]:
#So right side of A_I is the inverse
A_inv = A_I[:,3:]
print(A_inv)

[[ 2. -4.  5.]
 [-0. -1. -0.]
 [ 1. -1.  2.]]


### Question 2.1

Find the inverse of the **coefficient** matrix from the following system of equations:

> $x_1 + x_2 + 2x_3 = 8 $

> $-x_1 - 2x_2 + 3x_3 = 1 $

> $3x_1 - 7x_2 + 4x_3 = 10 $

If the inverse does not exist, write/print *DNE*. Show all row operations on paper and using your code.


In [ ]:
# your code here (after you calculate it by hand)

### Question 2.2
Find the inverse of the **coefficient** matrix from the following system of equations:

> $x_1 - 3x_2 + 4x_3 = 7 $

> $x_3 = 5 $

> $x_2 + 2x_3 = 2 $


In [ ]:
# your code here (after you calculate it by hand)

### Question 2.3

Find the inverse of the **coefficient** matrix from the following system of equations:

> $x_1 - 3x_3 = -2 $

> $3x_1 + x_2 - 2x_3 = 5 $

> $2x_1 + 2x_2 + x_3 = 4 $

If the inverse does not exist, write/print *DNE*. Show all row operations on paper and using your code.

In [ ]:
# your code here (after you calculate it by hand)

### Question 2.4

Find the inverse of the **coefficient** matrix from the following system of equations:

> $2x_1 + 2x_2 + 2x_3 = 0 $

> $-2x_1 + 5x_2 + 2x_3 = 1 $

> $8x_1 + x_2 + 4x_3 = -1 $

If the inverse does not exist, write/print *DNE*. Show all row operations on paper and using your code.

In [ ]:
# your code here (after you calculate it by hand)

## 3. Finding the Solution using the Inverse [5 pts each]

Recall:

Matrices can only be multiplied if their inner dimensions are equal. Multiplying $A$ with dimensions $m$ x $n$, by $B$ with dimensions $n$ x $p$, results in a matrix $AB$ of size $m$ x $p$.

<img src="https://lh3.googleusercontent.com/pw/ADCreHcSe-OO0Eh4TlZyt0RYkgpbCN79xoF0AUhV7yAJZWp1a-miuOhNnOR_M2zjdX14guNXEhFzT144A-bOzLDoSc_OLo_50S5DNwSIJot7mDI1xsvrDkrfjAXSuXsHIiFgzc0JxZ_6mGEEC2M6TR_w3jcv=w584-h371-s-no?authuser=0" width="350">

Matrix multiplication follows the row-column rule.

<img src="https://lh3.googleusercontent.com/pw/ADCreHdYJ6RYsDC9eDW-1SuX4Q1MdewyfC4pCMF9r3vOKesFMTrTkqF-JklZSAxXk0p0MVioYObI405XxPpVSVkQayTJsi_Js9-NSrLm932t1gsNvWU680Jrs_4D5n_iJo3HoEu-aZGT8G_8O2BsQy_gDUsk=w1400-h848-s-no?authuser=0" width="350">



If we have a system of equations represented as:

$$Ax = b$$

We can *left* multiply both sides by $A^{-1}$:

$$A^{-1}Ax = A^{-1}b$$

And since $A^{-1}A = I$:

$$Ix = A^{-1}b$$

So

$$x = A^{-1}b$$




### Question 3.1

Using $A$, $b$ and $A^{-1}$ from Question 2.1,

Use matrix multiplication to show that:

> $A A^{-1} = I$.

> $A^{-1} A  = I$.

> $x = A^{-1} b$, where $x$ is a vector containing the solutions.

Show all steps (as in the figure above) by hand. Check your work using Python where `@` is the operator used for matrix multiplication. 

If $A$ does not have an inverse, instead write and print to the screen "Not possible. Inverse does not exist".

In [ ]:
# your code here (after you calculate it by hand)

### Question 3.2

Solve for x in Question 2.2 using matrix multiplication:

> $x = A^{-1} b$, where $x$ is a vector containing the solutions.

Show all steps by hand. Check your work using Python where `@` is the operator used for matrix multiplication. 

If $A$ does not have an inverse, instead write and print to the screen "Not possible. Inverse does not exist".

In [ ]:
# your code here (after you calculate it by hand)

### Question 3.3

Solve for x in Question 2.3 using matrix multiplication:

> $x = A^{-1} b$, where $x$ is a vector containing the solutions.

Show all steps by hand. Check your work using Python where `@` is the operator used for matrix multiplication. 

If $A$ does not have an inverse, instead write and print to the screen "Not possible. Inverse does not exist".


In [ ]:
# your code here (after you calculate it by hand)

### Question 3.4

Solve for x in Question 2.4 using matrix multiplication:

> $x = A^{-1} b$, where $x$ is a vector containing the solutions.

Show all steps by hand. Check your work using Python where `@` is the operator used for matrix multiplication. 

If $A$ does not have an inverse, instead write and print to the screen "Not possible. Inverse does not exist".


In [ ]:
# your code here (after you calculate it by hand)